### ISSUE TITLE
Paypal IPN: how to implement?

### ISSUE THREAD

**Issue by wesleywillians** [Payum/PayumBundle#105]
Hi Folks,

I am using this bundle as recurring payment.
I would like to know:
- Do I need to create a controller to receive the paypal notification as well (for the IPN), or Is there anything (any route) ready to get and persist the notifications via IPN.

Can you guys provide me any docs/examples about this subject. I only saw  this link referencing about IPN (https://github.com/Payum/Payum/blob/master/docs/paypal/ipn/get-it-started.md)

**Comment by binarious** [comment]
@makasim Could you provide an example or can I just use http://payum.org/doc/1.0/Core/instant-payment-notification and handle that like in my gist in 1.0? I'm still on 0.8 and want to migrate to 1.0.
