### ISSUE TITLE
Handling recurring payment ipn

### ISSUE THREAD

**Issue by Misiur** [Payum/PayumBundle#116]
Hello there. I can't quite grasp how to handle ipn messages for recurring payments. First of all: you can't pass notify_url, and only option is static url set in the paypal account. Second of all, custom field doesn't cooperate, and only way to pass custom variables is via PROFILEREFERENCE/rp_invoice_id. Only 2 provided by PayumBundle notify routes require either token, or payment name. So - variables, which are not available for recurring payments... How should I securely handle this?

**Comment by silasrm** [comment]
@Misiur how yout set the custom field on recurrency?
