### ISSUE TITLE
Paypal and returnurl have no confirm button

### ISSUE THREAD

**Issue by Bernicia** [Payum/PayumBundle#153]
Hi,

I'm a bit confused - everything is pretty much OK, but on Paypal the only button you get is 'continue', and it clearly states that the buyer will confirm back on the site. But when you get back to the site, it's just status success, and the merchant can accept the payment on Paypal. Even if you manually gave the return url a confirm button, that wouldn't tell paypal anything and as far as the merchant is concerned it has been paid. As far as the customer is concerned, he never clicked confirm anywhere.

(edited to add - the same thing happens with your demo site)

thanks in advance for your advice and help

**Comment by jbartfay** [comment]
If Payum only supports a one-step process, shouldn't it set `useraction=commit` by default?

**Comment by makasim** [comment]
Payum not only supports one-step process, you are free to do whatever you want.

**Comment by jbartfay** [comment]
I propose an update: 389de94bc9d65209ced0909d37057b67344c2203

Should I setup a pull request?
