### ISSUE TITLE
Adding to notify controller.

### ISSUE THREAD

**Issue by Bernicia** [Payum/PayumBundle#157]
Hello, I have notify working with payum_notify_do route, but I need to do some extra processing (such as refund etc) What is the easiest way to do that - is it overriding the controller - I tried that bu the route payum_notify_do is set in payum bundle config for notify token creation, and I'm not sure of the best way top do this.

thanks

**Comment by gtrias** [comment]
Hey @makasim It seems you web site payum.org has been hacked :(

**Comment by makasim** [comment]
@gtrias nope. I haven't prolonged DNS name. The site is here https://payum.forma-pro.com/

How did you get there?

**Comment by gtrias** [comment]
Ok, I followed the link you provided above (looking for information about custom action usage)
