### ISSUE TITLE
[form] Error about Datetime expiration date

### ISSUE THREAD

**Issue by JulesLagadic** [Payum/PayumBundle#187]
Hello,

I installed PayumBundle stable version on Symfony 2.5.5. Everything is ok except when i submit the credit card form (i tried with be2bill credit card payment gateway). I've got a strange error about Datetime format : 

Notice: Object of class DateTime could not be converted to int in /var/www/dev/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 86

It seems to come from the expirationAt input of the form.

What could be the solution to solve that ?

Thank you,

**Comment by makasim** [comment]
not reproduced
