### ISSUE TITLE
Attempted to call method "createModel" 

### ISSUE THREAD

**Issue by xorgxx** [Payum/PayumBundle#210]
hi i just update bundle to today, it simce that i get error with this code : 

```
  - Updating payum/core dev-master (263d332 => a8eae72)
    Checking out a8eae724182095c4b0ee4334e6d34c5d3d94fa9a

  - Updating payum/payum-bundle dev-master (1ae61f2 => de9b33a)
    Checking out de9b33a26bbd9d99f82f11fc4a04ef26443c92e0

  - Updating payum/paypal-express-checkout-nvp dev-master (9f6573f => bbc8044)
    Checking out bbc8044b3ed90175c9d80b024cd73140f3034265
```

```
    $storage = $this->get ( 'payum' )->getStorage ( 'Neo\PaymentBundle\Entity\PaymentDetails' );
    $paymentDetails = $storage->createModel();
```

it return : 

```
Attempted to call method "createModel" on class "Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage". 
```

thank for help me.

**Comment by darkbluesun** [comment]
I just encountered this problem and solution in the stable branch!

Attempted to call method "createModel" on class "Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage". 

        "payum/payum-bundle": "*@stable",
        "payum/offline": "*@stable",
        "payum/paypal-express-checkout-nvp": "~0.12",

`$payment = $storage->createModel();` -> `$payment = $storage->create();` solves the problem

Have you written your software without considering backwards compatibility?

**Comment by darkbluesun** [comment]
I also get this message:

Attempted to call method "findModelByIdentificator" on class "Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage".

**Comment by makasim** [comment]
The dependencies is not good:

```
"payum/payum-bundle": "*@stable",
    "payum/offline": "*@stable",
    "payum/paypal-express-checkout-nvp": "~0.12",

```

stable now is 0.13 but paypal is still 0.12, 0.12 and 0.13 are not compatible. See https://github.com/Payum/Payum/blob/master/UPGRADE.md

**Comment by darkbluesun** [comment]
Would you suggest then?

    "payum/payum-bundle": "~0.12",
    "payum/offline": "~0.12",
    "payum/paypal-express-checkout-nvp": "~0.12",

Also, I see that `findModelByIdentificator` has been re-named to `find`. This is a scary thing to do. Setting up some kind of alias from the old name to the new would be advisable.

**Comment by darkbluesun** [comment]
My `composer.lock` says `paypal-express-checkout` is at `v0.13`

     "name": "payum/paypal-express-checkout-nvp",
     "version": "0.13.0",

**Comment by darkbluesun** [comment]
I'm happy to report that changing `findModelByIdentificator` to `find` solves the problem for me.

**Comment by darkbluesun** [comment]
Lastly, the version numbers 0.12 and 0.13 denote a minor version update, not a major upgrade. You should not make changes in minor versions that break functionality. Save that for version 0.2.

**Comment by makasim** [comment]
> You should not make changes in minor versions that break functionality.

Following semver I can do whatever changes I want at any time. Still I am trying to follow kind of release cycle. There was 0.1, 0.2...0.8,0.9.....0.12,0.13 versions. 

0.2 was already released long time ago.
