### ISSUE TITLE
Error after last composer.update

### ISSUE THREAD

**Issue by crevillo** [Payum/PayumBundle#227]
Hi there. after last update i've get an error coming from payum bundle. error looks 
like ```Catchable Fatal Error: Argument 3 passed to Payum\Core\Registry\AbstractRegistry::__construct() must be of the type array, string given, called in...```

Could it be due how the service is defined? What should we do to make it work again? 

Ref: https://github.com/Payum/PayumBundle/blob/master/Resources/config/payum.xml#L13

Thanks!

**Comment by makasim** [comment]
yeap, I haven't had time to update the bundle, the registry in core was changed in this PR: https://github.com/Payum/Payum/pull/302

**Comment by makasim** [comment]
The third parameter was a default payment name which I removed. And after that I added an array of payment factories as third parameter.

**Comment by crevillo** [comment]
yes, saw that. so, do you have an example of how could our config files look after this change?

**Comment by makasim** [comment]
Was fixed, try to upgrade bundle again.

**Comment by crevillo** [comment]
I'll do it tomorrow. Maybe would be good to update doc too?
