### ISSUE TITLE
Token still in database

### ISSUE THREAD

**Issue by Tetdoss** [Payum/PayumBundle#230]
Hello, I don't think it is an issue but I need to understand.

I'm using PayumBundle with Symfony2 and more precisely, Paypal express checkout.

Each time somebody initialize a Paypal payment, I have 2 new entry in payment_token (in my database), and when the payment is successful, I have 1 entry left in database, in which I can see target_url and when I use this url, it credits the user again. Is it secure ? Can the user see this target_url to get infinite credits ? I want to be sure about it.
And is it normal that we can spam by initialize a transaction and so have a lot of token and payment details in database which will be never removed ?

Moreover, I wonder where can I add modification on payment_details, I extended PaymentDetails with my User objet, and I want to add the amount of credit a user buy in PaymentDetails so that I can give him these credits when the payment is done. Is it a good way to do ?
Is it good use to get information on the transaction by using the json details in PaymentDetails like the date of the transaction... ?

Sorry for all these questions but I didn't find good examples.

Thanks, Tetdoss from France

**Comment by makasim** [comment]
>  I have 1 entry left in database, in which I can see target_url and when I use this url, it credits the user again. Is it secure ? 

is it payment/notify/xxx url?  is is what expected to be left in database and only your app and paypal side knows about it. a user have must not see it or have access ever to it.

**Comment by makasim** [comment]
> And is it normal that we can spam by initialize a transaction and so have a lot of token and payment details in database which will be never removed ?


You can easily add expire_at field and remove them by cron, for example

**Comment by makasim** [comment]
> User objet, and I want to add the amount of credit a user buy in PaymentDetails so that I can give him these credits when the payment is done. Is it a good way to do ?

you can do what ever you need in payment done action, most likely you want to find out the payment status and if it for example captured or authorized: credit a user, this is normal practice.

> Is it good use to get information on the transaction by using the json details in PaymentDetails like the date of the transaction... ?

it depends on how you organize code, in the simplest cases this valid scenario.

> Sorry for all these questions but I didn't find good examples.

Feel free to ask any further questions if something still not clear to you.

**Comment by Tetdoss** [comment]
Thank you for your answers, I'm feeling better using your bundle !

I have one question left, I wonder if it is easy to not use paypal but use directly credit card number ?
It doesn't matter me because PayPal works fine but maybe in the future I will need it. So if you can tell me the mainly step to do that, I will thank you again. I didn't find a short documentation about it, it seems to me very difficult to do.

Tetdoss

**Comment by makasim** [comment]
> I have one question left, I wonder if it is easy to not use paypal but use directly credit card number ?

you can try paypal pro checkout, stripe, authorize.net. All of them works with credit card

**Comment by Tetdoss** [comment]
Ok I See, I was not sure we must use a service like stripe or authorize to do it. In fact PayPal taxes about 2% and I wonder if we can avoid this taxe, but I think all these services taxe. But it doesn't matter a lot :)

Thanks
