### ISSUE TITLE
Empty order summary in paypal

### ISSUE THREAD

**Issue by graturi1** [Payum/PayumBundle#234]
Hi !
 My code is redirecting to paypal with empty order summary here is the controller prepare action:-

    public function prepareAction(Request $request)
    {
        if ($request->getMethod() == 'POST') {
            $amount = $request->request->get('amount');        
        $paymentName = 'paypal_us';
        $storage = $this->get('payum')->getStorage('Crowdfunding\FrontBundle\Entity\Order');
        $order = $storage->create();
        $order->setNumber(uniqid());
        $order->setCurrencyCode('EUR');
        $order->setTotalAmount($amount);
        $order->setDescription('A description');
        $order->setClientId('anId');
        $order->setClientEmail('foo@example.com');
        $storage->update($order);
        $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
            $paymentName,
            $order,
            'done_paypal' // the route to redirect after capture
        );

        return $this->redirect($captureToken->getTargetUrl());
    }
}

and my done action is:-

public function doneAction(Request $request)
    {
        $token = $this->get('payum.security.http_request_verifier')->verify($request);

        $payment = $this->get('payum')->getPayment($token->getPaymentName());

        // you can invalidate the token. The url could not be requested any more.
        // $this->get('payum.security.http_request_verifier')->invalidate($token);

        // Once you have token you can get the model from the storage directly.
        //$identity = $token->getDetails();
        //$order = $payum->getStorage($identity->getClass())->find($identity);

        // or Payum can fetch the model for you while executing a request (Preferred).
        $payment->execute($status = new GetHumanStatus($token));
        $order = $status->getFirstModel();

        // you have order and payment status
        // so you can do whatever you want for example you can just print status and payment details.

        return new JsonResponse(array(
            'status' => $status->getValue(),
            'order' => array(
                'total_amount' => $order->getTotalAmount(),
                'currency_code' => $order->getCurrencyCode(),
                'details' => $order->getDetails(),
            ),
        ));
    }

what i am doing wrong here and what code add here for sending the summary detail to paypal...

**Comment by graturi1** [comment]
it also being save the data in details field in database that is :-
{"INVNUM":"54c76ce901847","PAYMENTREQUEST_0_CURRENCYCODE":"EUR","PAYMENTREQUEST_0_AMT":54.36,"PAYMENTREQUEST_0_NOTIFYURL":"http:\/\/localhost\/nxt-starter-paypal\/web\/app_dev.php\/payment\/notify\/9ytOOJ2hQEu27SqeBTcyUmPvwysJ_kvydtgomjqiWA8","PAYMENTREQUEST_0_PAYMENTACTION":"Sale","RETURNURL":"http:\/\/localhost\/nxt-starter-paypal\/web\/app_dev.php\/payment\/capture\/AvwmbjeMQHk-a3rKT8c2uUOcj8btYpiv_s6ms75QISA","CANCELURL":"http:\/\/localhost\/nxt-starter-paypal\/web\/app_dev.php\/payment\/capture\/AvwmbjeMQHk-a3rKT8c2uUOcj8btYpiv_s6ms75QISA","TOKEN":"EC-94439861NA647162N","TIMESTAMP":"2015-01-27T10:48:11Z","CORRELATIONID":"e8feea5b82cd","ACK":"Success","VERSION":"65.1","BUILD":"15009693"}

**Comment by makasim** [comment]
you can set paypal specific fields explicitly like this (of cource you can add any other paypal's fields):

```
$order->setDetails([
    'L_PAYMENTREQUEST_0_DESC0' => 'A desc',
]);
```

or you can extend [FillOrderDetailsAction](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/FillOrderDetailsAction.php) paypal's action. That's super easy to do in master, just define a container service, tag it with alias:

```
fill_details_action:
  class: Foo
  tags:
    - { name: "payum.action", factory: paypal_express_checkout_nvp, alias: fill_order_details }
```

**Comment by graturi1** [comment]
Thank you so much @makasim  its works for me :+1:
