### ISSUE TITLE
How to update order without notify URL payum_token?

### ISSUE THREAD

**Issue by belendel** [Payum/PayumBundle#236]
Hi,

First of all thank you for all the great work! I just found out about payum and am still trying to wrap my head around everything. I am trying to add a new payment service provider into my symfony project. The psp does not provide the ability to set a dynamic notify URL. In de psp panel i can set a single URL. Also I cannot send any extra variables that will be sent back with the pushes. So far I have made the following steps:

1) Add order number to payment token entity
2) Create custom notify controller that extends PayumController. I use this controllers route as callback URL for the psp.
3) Override the getHttpRequestVerifier method to get my own verifier service
4) The verifier service returns the token found by order number
5) In my Notify execute method i replace the status in order details

When i dump order details i see everything get updated. Two questions:

1) Is my approach the right way? Would there be any better solutions?
2) Why is my model not being persisted. What is the best way to do this?

Any help would be appreciated!

**Comment by belendel** [comment]
Seems i have found the issue. When you return to the symfony application a new token is created and the order number column was set to null. 

I have not found a fix for this yet. Finding the token by order number does not seem like the best solution to me. However I can't think of anything better right now. Hopefully someone can point me into the right direction.

**Comment by makasim** [comment]
You can generate a notify url with the [command](https://github.com/Payum/PayumBundle/blob/master/Command/CreateNotifyTokenCommand.php#L21) . Without the model associated of course.  Put it to payment backend as a notify url. Then you have to develop and register an action which handled the notification, something like [this](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Payum/Be2bill/Action/NotifyAction.php).

**Comment by makasim** [comment]
> 2) Why is my model not being persisted. What is the best way to do this?

If you configured a storage for your model it must be auto saved.

**Comment by makasim** [comment]
Feel free to ask any other question you may have.

**Comment by belendel** [comment]
>There is a simpler one. Basically you have to create your own notify action and a notify url without the >model

>You can generate a notify url with the command . Without the model associated of course. Put it to >payment backend as a notify url. Then you have to develop and register an action which handled the >notification, something like this.

I got this working now. It's a better solution with cleaner code  :+1: 

>If you configured a storage for your model it must be auto saved. Could you post your payum config >please?

Was an error in my code.

Thank you for the help makasim!
