### ISSUE TITLE
how to detect/handle exception

### ISSUE THREAD

**Issue by shairyar** [Payum/PayumBundle#239]
A  documentaion on how to handle exceptions, for example how to handle creditcard check exceptions would it really helpfull

**Comment by makasim** [comment]
You can do it outside Payum like this (or register to an exception event if you use a framework).

```php

try { 
    $payment->execute($request);
} catch (\Exception $e){
    // do something
}
```

or you can register an extension, [like this](https://github.com/Payum/PayumBundle/blob/master/Resources/config/payum.xml#L55) and put the code to onException method.

**Comment by shairyar** [comment]
Thanks alot, I will try your suggestion and get back

**Comment by shairyar** [comment]
I am using payumBundle and this is how I am trying to catch the exception
<code>
                    $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
                        $paymentName,
                        $details,
                        'payment_done' // the route to redirect after capture;
                    );

                   try {
                        return $this->forward('PayumBundle:Capture:do', array(
                            'payum_token' => $captureToken,
                        ));

                    } catch (\Exception $e) {
                        $exceptions = array();
                        do {
                            $exceptions[] = $e->getMessage();
                        } while ($e = $e->getPrevious());
                        $response = new Response(json_encode(array('status' => 'failed', 'Message' => $exceptions)));
                        return $response;
                    }
</code>

The error i see when i enter wrong card is as following

Card number is invalid
500 Internal Server Error - InvalidCreditCardException 

I would like to display a user friendly message. 
Please help as i am fairly new to symfony and payum
