### ISSUE TITLE
Masspay by payum

### ISSUE THREAD

**Issue by graturi1** [Payum/PayumBundle#242]
Hi !
How do to implement masspay by payum.I am trying to recieve payment using paypal's different-2 email address but there is a setting for one account , so can we do masspay by payum.....
  
Thank you

**Comment by makasim** [comment]
Are you talking about Paypal [AdaptivePayments](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/). I know it is possible to send money from one Paypal account to another one(s). Is it what you are looking for?

**Comment by graturi1** [comment]
yes i am looking for AdaptivePayments. Can i do it with payum ..??.In Previous i set up the payum for one reciever .

**Comment by makasim** [comment]
It is possible but the extension is still "work in progress": https://github.com/Payum/Payum/pull/172

**Comment by graturi1** [comment]
so i have to use inline Php code for it now.

**Comment by makasim** [comment]
closing than

**Comment by graturi1** [comment]
Makasim, is there any solution because I am using payum also in different transactions on same application. Let me how can I use payum for adaptive payment.

**Comment by makasim** [comment]
Well there three solutions:

* Create your own Payum extension.
* Finish the one I mentioned. 
* Hire me so I do it for you.
