### ISSUE TITLE
What is the purpose of notification?

### ISSUE THREAD

**Issue by shairyar** [Payum/PayumBundle#247]
Hi,

I am looking at the sandbox of payumBundle and i am trying to understand the purpose of why this folder exist https://github.com/makasim/PayumBundleSandbox/tree/master/src/Acme/PaymentBundle/Payum.

What is the purpose of the Action and Extention? Do they save anything in database? If yes what? I will really appreciate a detailed response.

**Comment by makasim** [comment]
The action and extension are described here: http://payum.org/doc/0.14/Core/the-architecture. Here you can read about storages: http://payum.org/doc/0.14/Core/storages

> What is the purpose of notification?

I guess you are asking about a push notification which a gateway may send us. Something like https://developer.paypal.com/docs/classic/products/instant-payment-notification/

**Comment by shairyar** [comment]
Hi,

I understand the purpose of push notifications (IPN) however I just wanted to understand the pupose of the following

My paypal integration is working perfectly fine without creating any of the following
https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Resources/config/services.yml
and the code at https://github.com/makasim/PayumBundleSandbox/tree/master/src/Acme/PaymentBundle/Payum.

I also notice database table called "NotificationDetails" but it always stays empty, what is this table for?


Currently all the paypal related details are being saved inside table called Orders and PaymentToken so what is table "NotificationDetails" for?

**Comment by makasim** [comment]
> My paypal integration is working perfectly fine without creating any of the following

The sandbox contains different examples, some of them require those service. Please note that this sandbox is not meant to be used as  a base for your projects. It is just a place to learn about Payum and payments.

**Comment by makasim** [comment]
> I also notice database table called "NotificationDetails" but it always stays empty, what is this table for?

**Comment by shairyar** [comment]
> The sandbox contains different examples, some of them require those service. Please note that this sandbox is not meant to be used as a base for your projects. It is just a place to learn about Payum and payments.

Thanks and yes I know that sandbox is meant to learn about Payum and thats what I am doing, if you could kindly let me know the purpose of the following I will really appreciate it

NotificationsController, I know it is an example of something, but what are you trying to do in this example?
https://github.com/makasim/PayumBundleSandbox/treea/master/src/Acme/PaymentBundle/Resources/views/Notifications

Service, what is the purpose of this example?
https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Resources/config/services.yml

Table (NotificationDetails), what is the purpose of this table?

Many thanks, it is a really nice bundle and I am learning about it :)
