### ISSUE TITLE
Add recurring payment functionality to Stripe

### ISSUE THREAD

**Issue by mohamedragabdahab** [Payum/PayumBundle#249]
Give the ability to create new customer and new plans, hence recurring payment on stripe would be possible.

**Comment by makasim** [comment]
This an issue, Pull Request (PR) like this one: https://github.com/Payum/PayumBundle/pull/223

**Comment by mohamedragabdahab** [comment]
sorry i can not see any resemblance, are you sure they both are similar?

On Mon, Mar 23, 2015 at 9:36 PM, Maksim Kotlyar <notifications@github.com>
wrote:

> This an issue, Pull Request (PR) like this one: #223
> <https://github.com/Payum/PayumBundle/pull/223>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Payum/PayumBundle/issues/249#issuecomment-85160888>.
>



-- 

Best Regards,

Mohamed Ragab

Software Engineer

Cell: +201 006216723 | Skype: m_ragab333
facebook <https://www.facebook.com/mohamed.ragab.dahab> | Linkedin Profile
<https://www.linkedin.com/profile/view?id=95324964>
