### ISSUE TITLE
throw custom events after notifications

### ISSUE THREAD

**Issue by caxilomo** [Payum/PayumBundle#257]
after receiving a notification would be appropriate to launch a custom event if someone wants to make some extra action after the bundle do its job

**Comment by makasim** [comment]
There are a bunch of ways to hook into the process. You can add a custom action which does the job before the basic action. You can also register an extension and do some extra works there.


If you still want to dispatch events: There is an extension which does that: https://github.com/Payum/Payum/pull/294
