### ISSUE TITLE
dev master breaks compatibility

### ISSUE THREAD

**Issue by svassaux** [Payum/PayumBundle#261]
Hi had v0.14 installed and now 0.15 (or ~0.14 given my composer parameters) seems to breaks BC.

First simple change was 'payment' became 'gateways' in the config.yml

Once done, I'm for instance redirected to paypal when proceeding to a payment.
After login I have the following error in the paypal page :
(no error with 0.14):

How can we resolve this ?

PimpAbort with return code 4001
File: rapids/Merchant/Payment/Incentive/decorator/DecoratorIncentiveAnalysis.cpp
Func: execute Line: 115

Backtrace: Utility::WebPimpExceptionHandlerALIImpl::handle_PimpAbortException(PimpAbortException const&, Riprap::WebAppReturn&) Utility::WebPimpExceptionHandlerALIImpl::handle_exceptions(PPException const&, Riprap::WebAppReturn&) MerchantPaymentWeb::exception_handler(PimpWebAppContext const&, PPException const&, Riprap::WebAppReturn&) Riprap::dispatch_loop(Riprap::EPRegistry const&, Riprap::WebAppContext const&, Riprap::DispatchAction&, Riprap::WebAppReturn&, String const&, Riprap::DispatchInterceptorRegistry const&) Riprap::dispatch_wrapper(OutputStream&, Riprap::EPRegistry const&, Riprap::WebAppContext const&, Riprap::WebAppReturn const&, String const&, bool const&, Riprap::DispatchInterceptorRegistry const&) Riprap::entry_point(HTTPInterface&, Riprap::CGIVars&, OutputStream&, String const&, String const&) main

Use of pimp_rc (3013), Use of pimp_rc (14816), Use of pimp_rc (9449), Use of pimp_rc (9445), Use of pimp_rc (3507), Use of pimp_rc (4001), Use of pimp_rc (4002), Use of pimp_rc (3778), Use of pimp_rc (4007), Use of pimp_rc (4020), Use of pimp_rc (7003), Use of pimp_rc (3583), Use of pimp_rc (3051), Use of pimp_rc (3001), Use of pimp_rc (3021), Use of pimp_rc (3242), Use of pimp_rc (3165), Use of pimp_rc (3101), Use of pimp_rc (3085), Use of pimp_rc (3209), Use of pimp_rc (3174), Use of pimp_rc (3043), Use of pimp_rc (3241), Use of pimp_rc (3082), Use of pimp_rc (3129), Use of pimp_rc (3567), Use of pimp_rc (3235), Use of pimp_rc (3236), Use of pimp_rc (3508), Use of pimp_rc (3507), Use of pimp_rc (3531), Use of pimp_rc (3514), Use of pimp_rc (3124), Use of pimp_rc (3047), Use of pimp_rc (3224), Use of pimp_rc (3093), Use of pimp_rc (3253), Use of pimp_rc (3254), Use of pimp_rc (3083), Use of pimp_rc (3137), Use of pimp_rc (3256), Use of pimp_rc (14268), Use of pimp_rc (14267), Use of pimp_rc (14266), Use of pimp_rc (14269), Use of pimp_rc (14264), Use of pimp_rc (14265), Use of pimp_rc (14244), Use of pimp_rc (3084), Use of pimp_rc (3254), Use of pimp_rc (3083), Use of pimp_rc (3137), Use of pimp_rc (3070), Use of pimp_rc (3141), Use of pimp_rc (3198), Use of pimp_rc (3011), Use of pimp_rc (10021), Use of pimp_rc (3199), Use of pimp_rc (3015), Use of pimp_rc (3014), Use of pimp_rc (3200), Use of pimp_rc (3257), Use of pimp_rc (3012), Use of pimp_rc (3141), Use of pimp_rc (3535), Use of pimp_rc (3504), Use of pimp_rc (10022), Use of pimp_rc (6702), Use of pimp_rc (3001), Use of pimp_rc (3120), Use of pimp_rc (3517), Use of pimp_rc (3531), Use of pimp_rc (3201), Use of pimp_rc (3803), Use of pimp_rc (6834), Use of pimp_rc (3807), Use of pimp_rc (3808), Use of pimp_rc (3810), Use of pimp_rc (3812), Use of pimp_rc (3809), Use of pimp_rc (3805), Use of pimp_rc (2002), Use of pimp_rc (3177), Use of pimp_rc (3051), Use of pimp_rc (3510), Use of pimp_rc (4003), Use of pimp_rc (3013), Use of pimp_rc (4011), Use of pimp_rc (3300), Use of pimp_rc (3286), Use of pimp_rc (6681), Use of pimp_rc (14605), Use of pimp_rc (10361), Use of pimp_rc (14353), Use of pimp_rc (14817), Use of pimp_rc (4002), Use of pimp_rc (2001), Use of pimp_rc (4001), Use of pimp_rc (11045), Use of pimp_rc (3593), Use of pimp_rc (4071), Use of pimp_rc (3514), Use of pimp_rc (4022), Use of pimp_rc (4014), Use of pimp_rc (4011), Use of pimp_rc (9500), Use of pimp_rc (9501), Use of pimp_rc (11729), Use of pimp_rc (11728), Use of pimp_rc (4001), (rcf @ virtual int Merchant::PimpFeatureStatusBLIImpl::legacy_get_feature_status(ullong, PimpFeatureId, PimpFeatureStatus&):41)

Une erreur s'est produite.

Retour à la page d'accueil

**Comment by makasim** [comment]
There are lots of updates in library itself: https://github.com/Payum/Payum/blob/master/UPGRADE.md

and I forgot to update bundles UPGRADE file: https://github.com/Payum/PayumBundle/blob/0.15/UPGRADE.md

I'll do it

**Comment by makasim** [comment]
> Once done, I'm for instance redirected to paypal when proceeding to a payment.
> After login I have the following error in the paypal page :
> (no error with 0.14):

It could be tmp error, I tested Paypal lots of times before releasing it. It worked.

**Comment by svassaux** [comment]
thanks ! I did not find the upgrade.md, so I might be missing some elements. I'll check it and post an update
