### ISSUE TITLE
Execute payment after validation

### ISSUE THREAD

**Issue by guizm0b** [Payum/PayumBundle#269]
Hi,

I'm trying to use Payum with Stripe Checkout on my Symfony 2 website.
I was wondering if there is a way to execute a payment only when an administrator accept an order ?

For example, my customer comes to my website, add an item to his basket and fill the payment form with his card information and validate. Then, the order would be saved as "waiting for validation", but the payment is not processed. 
In my admin panel, I can see that order and when clicking on "Accept" the payment is processed.

Is that possible ? If yes can you give me the outlines ?

Thanks for your help

**Comment by makasim** [comment]
It is possible, just store payment details (do not create capture token and do not redirect to capture action) to database and send a mail to administrator. When the payment is accepted  send a mail to user with capture url link so he is able to pay.

There are other ways of implementation, It is totaly up to you how to tie everything together

**Comment by guizm0b** [comment]
Thanks for your answer, I'll do something like that.
