### ISSUE TITLE
Don't require Sonata if we disabled it

### ISSUE THREAD

**Issue by tristanbes** [Payum/PayumBundle#272]
Hi,

In a previous bug #255 it was added a possibility to remove sonata as a backend config.
But even if we do so, the bundle needs the Sonata project in our dependencies.

Is that possible to make this dependency optional when this feature is disabled and not require to use it via composer ?

```
PHP Fatal error:  Class 'Sonata\AdminBundle\Admin\Admin' not found in /home/travis/build/Yproximite/yProx/vendor/payum/payum-bundle/Sonata/PaymentConfigAdmin.php on line 10
```

**Comment by makasim** [comment]
It is indeed a good idea.

**Comment by tristanbes** [comment]
Hi, any news on this ? :)

**Comment by makasim** [comment]
nothing

**Comment by makasim** [comment]
Cannot reproduce it.

**Comment by makasim** [comment]
Though add a check to prevent fatal. https://github.com/Payum/PayumBundle/pull/309
