### ISSUE TITLE
Edit "payum.template.obtain_token"

### ISSUE THREAD

**Issue by allanbrault** [Payum/PayumBundle#276]
Hi,

I can't seen to find a way to edit the "payum.template.obtain_token" for stripe_js.

I tried to edit the parameters for the template, but nothing.
```
parameters:
    payum.stripe_js.template.obtain_checkout_token: PaymentBundle::test.html.twig
```

any idea on how to edit this template ? Thanks.

**Comment by makasim** [comment]
Yes that's correct, You have to edit this parameter. It is defined here: https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/Factory/Gateway/StripeJsGatewayFactory.php#L17

So it most probably a bug, but let's start from a simple check. Could you please run `app/console container:debug --parameters | grep payum` and see what is set to the parameter.
 
If it is set to `PaymentBundle::test.html.twig` I'd say there is a bug.

**Comment by allanbrault** [comment]
I think it's a bug
```
payum.stripe_js.template.obtain_checkout_token                        PaymentBundle::test.html.twig
```
and https://github.com/Payum/Payum/blob/0.15/src/Payum/Stripe/StripeJsGatewayFactory.php#L11 here the parameter $config doesn't have the key 'payum.template.obtain_token' defined.

**Comment by allanbrault** [comment]
Ok, on the 0.15 branch there was a bug that overwrited the $config['payum.template.obtain_token'], but in the master branch its fixed, thanks anyway.
