### ISSUE TITLE
Propel Tag

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#279]
Is it possible to add a propel tag onto the bundle so I can get this rather than having to use master?

**Comment by makasim** [comment]
Unfortunately I cannot do it right now , it would mean a release of 1.0.0 version which is not the case. I have plans to add some features which may have BC breaks.

We can try to cherry pick changes to 0.15 branch. Will it work for you?

**Comment by liamsorsby** [comment]
Don't worry about it I've included it in my composer file and then manually moved the files over. That way it's registered that the files are there without effecting it's dependancies. You can close this if you would like
