### ISSUE TITLE
Propel bug

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#280]
Trying propel 1. Seems that the model class is never passed through.

Error:
Attempted to load class "" from the global namespace.
Did you forget a "use" statement? 

vendor/payum/core/Payum/Core/Storage/AbstractStorage.php
```php
public function create()
{
  return new $this->modelClass();
}
```
No modelClass is ever sent over. Any thoughts so I can have a look into this?

**Comment by makasim** [comment]
no idea, should work

**Comment by liamsorsby** [comment]
@makasim For some reason removing one of the arguments out of propel1.xml and then removing the 1 from the factory remove arguments and changing it to 0 works. Do you want me to rebase and make a new pull request for you to have a look at?

**Comment by makasim** [comment]
A new PR with just the is fine.

**Comment by liamsorsby** [comment]
PR: #281
