### ISSUE TITLE
Error with the dev-master core version

### ISSUE THREAD

**Issue by mkurzeja** [Payum/PayumBundle#283]
> Error: Call to a member function createConfig() on a non-object in /vendor/payum/core/Payum/src/Payum/Core/GatewayFactory.php line 43

The reason for this error is that the bundle overrides the GatewayFactory constructor, but does not execute the overridden one (from Core) and CoreGatewayFactory is not created.

**Comment by makasim** [comment]
sorry, could you post some links to the code.

**Comment by mkurzeja** [comment]
Sure,

The Core GatewayFactory has a constructor that creates a CoreGatewayFactory instance:
https://github.com/Payum/Payum/blob/master/src/Payum/Core/GatewayFactory.php#L24

The bundle overrides this class and implements its own constructor:
https://github.com/Payum/PayumBundle/blob/master/GatewayFactory.php#L36

I believe a ```parent::__construct()``` would be enough to fix this, but I'm not sure if it is the best solution for this so I did not submit a PR.

**Comment by makasim** [comment]
> The bundle overrides this class and implements its own constructor:

The bundle extends CoreGatewayFacotry not GatewayFactory

**Comment by makasim** [comment]
> I believe a parent::__construct() would be enough to fix this, but I'm not sure if it is the best solution for this so I did not submit a PR.

The parent::__construct has to be added. But I dont think it can fix the issue because it is not that parent class you mentiond

**Comment by makasim** [comment]
@mkurzeja What was the problem?

**Comment by mkurzeja** [comment]
I somehow managed to get the wrong version of payum/payum-bundle. Not sure why, because I told compoer to get dev-master but it kept the older one. 

Tested now with the most recent one and it works.

Sorry
