### ISSUE TITLE
Add possibility to override Sonata Admin class

### ISSUE THREAD

**Issue by mkurzeja** [Payum/PayumBundle#286]
By extending GatewayConfig I can add new fields (ex. gateway logo), but there is no possibility to add such fields into admin.

A config value would probably be enough for most cases, but maybe there is a better way to do this.

**Comment by makasim** [comment]
You can overwrite the admin service.

**Comment by makasim** [comment]
try to overwrite the service `payum.dynamic_gateways.gateway_config_admin ` . it is defined here: https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/PayumExtension.php#L233

**Comment by mkurzeja** [comment]
That Was my first call, I've added my own extension:

```php
    public function load(array $config, ContainerBuilder $container)
    {
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.yml');

        $definition = $container->getDefinition('payum.dynamic_gateways.gateway_config_admin');
        $definition->setClass('Acme\TestBundle\Admin\GatewayConfigAdmin');
```

But I get an error: The service definition "payum.dynamic_gateways.gateway_config_admin" does not exist.

I would add a new service, but then I need to define the entity class twice (for the new admin service, and in payum config).
(The one used here https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/PayumExtension.php#L223)

I'll try some other ways to do this.

**Comment by mkurzeja** [comment]
Ok, the fastest solution is to add a compiler pass for this.

Thanks :)
