### ISSUE TITLE
HHVM Test Failure

### ISSUE THREAD

**Issue by inssein** [Payum/PayumBundle#288]
Does anyone know why the test fails on HHVM? Link: https://travis-ci.org/Payum/PayumBundle/jobs/68263279

I was just testing my application (which uses this bundle) with HHVM, and it crashed on that line as well.

**Comment by inssein** [comment]
The test fails on ```CreditCardTypeTest::shouldSubmitDataCorrectly```

**Comment by makasim** [comment]
HHVM is not officially supported
