### ISSUE TITLE
Moving to SemVer

### ISSUE THREAD

**Issue by myovchev** [Payum/PayumBundle#289]
I would like to propose [SemVer](http://semver.org) specification as a Payum releases standard. 
Currently Payum versioning is messing major with minor releases, which leads to things like this (from the last changelog):
```
Rename Payment and PaymentXXX classes to Gateway and GatewayXXX ones.
Rename Order to Payment.
Update configure-payment-in-backend.md
```
to break existing installations on all possible levels due to missing BC and public API refactoring. In terms of SemVer, the 0.15 release would be major one. Minor releases would point deprecation, future major changes breaking the current public API, which give us (poor devs :) ) time to prepare for those changes and keep our apps stable (sticking to minor version which grants us stable behaviour).

**Comment by makasim** [comment]
Payum is in pre 1.0 phase and according to SemVer 

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Though I tried to do BC breaks only between versions like 0.14.x to 0.15.x and never between 0.15.1 to 0.15.2 for example. 

I'll do it to easier your life even though SemVer does not force me to do so.

Of cource there will not any BC breaks once 1.0.0 is released.

**Comment by myovchev** [comment]
Thanks, I wasn't aware of those facts :)

**Comment by makasim** [comment]
From now on, any BC breaks: https://github.com/Payum/PayumBundle/releases/tag/1.0.0-BETA1
