### ISSUE TITLE
Omnipay/Mollie gateway not working

### ISSUE THREAD

**Issue by goemaere** [Payum/PayumBundle#290]
I am trying to configure the PayumBundle with the OmnipayBridge to the Omnipay/Mollie Gateway.
This is my configuration:

    payum:
        payments:
            mollie:
                omnipay_offsite:
                    type: Mollie
                    options:
                        apiKey: test_R78.......

After the finalize step in the checkout I get redirected to the Mollie payment page. So far so good.

After (test) payment I get redirected back to my webshop @ http://www.inserturlhere.com/payment/capture/{some_payum_token}
On this page I get the following exception: The transactionReference parameter is required 
This exception is thrown @ Omnipay\Mollie\Message\CompletePurchaseRequest::getData().
The transactionReference parameter is indeed null.

A similar issue is marked as closed @ https://github.com/thephpleague/omnipay-mollie/issues/18
Am I missing something in my config for the PayumBundle? Or is it a bug? 

Libraries used:
- Sylius 0.14
- Omnipay-bridge 0.14.2
- Payum 0.14.5
- Payum Bundle 0.14.4
- Omnipay/mollie 3.0.4

**Comment by makasim** [comment]
Looks like a bug,

**Comment by makasim** [comment]
have you found anything?

**Comment by goemaere** [comment]
Sorry for my late answer. Only just figured this out.
The OmnipayBridge\OffsiteCaptureAction::execute() method does not set the correct parameters for the Omnipay/Mollie gateway. 

The lines in following URL
https://github.com/Payum/OmnipayBridge/blob/master/src/Action/OffsiteCaptureAction.php#L41-L43
should be replaced by:
```php
        if (false == $details['returnUrl'] && $request->getToken()) {
            $details['returnUrl'] = $request->getToken()->getAfterUrl();
        }

	if (false == $details['notifyUrl'] && $request->getToken()) {
		$details['notifyUrl'] = $request->getToken()->getTargetUrl();
	}
```

**Comment by makasim** [comment]
@goemaere Replaced with what?

**Comment by goemaere** [comment]
I've made a fork and replaced these lines:
```php
        if (false == $details['returnUrl'] && $request->getToken()) {
            $details['returnUrl'] = $request->getToken()->getTargetUrl();
        }
```
with these lines:
```php
		if (false == $details['returnUrl'] && $request->getToken()) {
			$details['returnUrl'] = $request->getToken()->getAfterUrl();
		}
	
		if (false == $details['notifyUrl'] && $request->getToken()) {
			$details['notifyUrl'] = $request->getToken()->getTargetUrl();
		}

```
in this file:
https://github.com/Payum/OmnipayBridge/blob/master/src/Action/OffsiteCaptureAction.php#L41-L43

But like I said, these changes work for the Omnipay/Mollie gateway, but the changes are probably not compatible with other gateways. Maybe the returnUrl, notifyUrl, cancelUrl ... should be configurable in some way?

**Comment by makasim** [comment]
It does not make any sense. I guess the omnipay gateway has to be fixed.

**Comment by parveensaini5** [comment]
Here's how I solved this issue.

if($response->isRedirect()){
			$this->session->set_flashdata('reference', $response->getTransactionReference()); // SAVE TRANSACTIONREFERENCE IN SESSION TEMPORARILY AND USE  IT IN COMPLETEPURCHASE METHOD
			$response->redirect(); 
		} elseif($reponse->isPending()) {
			return "Pending, Reference: ". $response->getTransactionReference();
		} else {
			return "Error " .$response->getCode() . ': ' .$response->getMessage();
		}

**Comment by steffenbrem** [comment]
Having the same issues, is there anyone with a proper fix for this?

**Comment by steffenbrem** [comment]
@makasim What do you think about the following patch? After the payment is created by mollie, I get the transaction reference and set it on the payment details. This way it is stored with the payment in the database, and since those data are passed to the omnipay gateway, it works. 

Should I submit a PR with this fix? Or do you see a better way to solve this problem.

```php
$response = $this->omnipayGateway->purchase($details->toUnsafeArray())->send();

// this fixes all issues everyone is having, without messing with existing providers
$details['transactionReference'] = $response->getTransactionReference();
```
