### ISSUE TITLE
DoAction issue on symfony2 paypalexpresscheckoutnvp

### ISSUE THREAD

**Issue by polantis** [Payum/PayumBundle#294]
Hello,

Each time i try to use payum for a payment i have got this issue:

The current url http://domain.com/payment/capture/********_**************_***************_* not match target url http://domain.com/paymentdone?payum_token=***************************_************** set in the token. 

When i check database i always have 2 entries in PaymentToken. Is it normal?

By the way, I never see any paypal page to pay for anything.

I have followed these tutorials:
http://payum.org/doc/0.15/PaypalExpressCheckoutNvp/get-it-started
http://payum.org/doc/0.15/PayumBundle/get_it_started

Thank you for your help !

**Comment by makasim** [comment]
most likely your credentials are not valid, a type in signature for example, and you are getting an error. Look for errors in your payment details.

> When i check database i always have 2 entries in PaymentToken. Is it normal?

Yes, that's expected.

**Comment by polantis** [comment]
Hello,

Thank you for your answer.

I am using credentials from paypal API Module (version 93 in php). By the way i do not know where to add sBNCode. Should i create other credentials?

Thank you

**Comment by polantis** [comment]
Hello,

I am having the same issue when using offline gateway so I do not think it is related to credentials. What would you suggest?

Thank you

**Comment by polantis** [comment]
Hello,

After debugging the issue, the issue seems to be in the redirection or in payum_capture_do.

Here is a dump of PaymentToken before redirection
PaymentToken {#571 ▼
  #details: Identity {#596 ▶}
  #hash: "br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw"
  #afterUrl: "www.domain.com/paymentdone?payum_token=ci--JFFifMvHr7quDXLPDKC2CV97iKHVBmAGvfteSNk"
  #targetUrl: "www.domain.com/payment/capture/br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw"
  #gatewayName: "offline"
}

You can find below the logs after the redirection:

    INFO - Matched route "payum_capture_do".
    Context: {"route_parameters":{"_controller":"Payum\\Bundle\\PayumBundle\\Controller\\CaptureController::doAction","payum_token":"br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw","_route":"payum_capture_do"},"request_uri":"www.domain.com/payment/capture/br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw"}

    INFO - Populated the TokenStorage with an anonymous Token.
    ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "The current url www.domain.com/payment/capture/br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw not match target url www.domain.com/paymentdone?payum_token=yHphH3t794OOIwxl5ZPsL0Smc8MG_KrqHOudXs7AvIM set in the token." at /vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Security/HttpRequestVerifier.php line 52
    Context: {"exception":"Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException)"}

Why is the payum token different?

Help me please !
Thank you

**Comment by makasim** [comment]
Something wrong in the config, or our code.

```
The current url www.domain.com/payment/capture/br60ymQRCyD8xBmqndZrd-lVb7DDrN-ATJqXK_s6Idw not match target url www.domain.com/paymentdone?payum_token=yHphH3t794OOIwxl5ZPsL0Smc8MG_KrqHOudXs7AvIM
```

Tells that you are trying to use capture token as a done one. That's not correct

**Comment by polantis** [comment]
Thank you for your answer. What should be displayed on capture time?

Here is my code:


Controller
public function prepareAction()
    {
        $gatewayName = 'offline';

        $storage = $this->get('payum')->getStorage('POL\PaymentBundle\Entity\***');

        $payment = $storage->create();
        $payment->setNumber(uniqid());
        $payment->setCurrencyCode('EUR');
        $payment->setTotalAmount(123); // 1.23 EUR
        $payment->setDescription('A description');
        $payment->setClientId('anId');
        $payment->setClientEmail('foo@example.com');
****

        $storage->update($payment);

        $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
            $gatewayName,
            $payment,
            'done' // the route to redirect after capture
        );

        dump($captureToken);

        return $this->redirect($captureToken->getTargetUrl());
    }

 public function doneAction(Request $request)
    {
        //return new Response(var_dump($request));

        $token = $this->get('payum.security.http_request_verifier')->verify($request);

        $gateway = $this->get('payum')->getGateway($token->getGatewayName());

        // you can invalidate the token. The url could not be requested any more.
        // $this->get('payum.security.http_request_verifier')->invalidate($token);

        // Once you have token you can get the model from the storage directly.
        //$identity = $token->getDetails();
        //$payment = $this->get('payum')->getStorage($identity->getClass())->find($identity);

        // or Payum can fetch the model for you while executing a request (Preferred).
        $gateway->execute($status = new GetHumanStatus($token));
        $payment = $status->getFirstModel();

        // you have order and payment status
        // so you can do whatever you want for example you can just print status and payment details.

        return new JsonResponse(array(
            'status' => $status->getValue(),
            'payment' => array(
                'total_amount' => $payment->getTotalAmount(),
                'currency_code' => $payment->getCurrencyCode(),
                'details' => $payment->getDetails(),
            ),
        ));
    }

routing.yml
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

done:
  path:    /paymentdone
  defaults: { _controller: ACMEPaymentBundle:Payment:done }

pol_paymenttest:
  path:    /paymenttest
  defaults: { _controller: ACMEPaymentBundle:Payment:prepare }

Thank you

**Comment by polantis** [comment]
What could be wrong?
Please help

**Comment by polantis** [comment]
Hello again,

I am still having the same mistake. When is the capture done? When should I have paypal pages? 
It seems that i am redirected directly to done method. I thought that createCaptureToken was launching the capture process.

Thank you for your help!

**Comment by makasim** [comment]
>most likely your credentials are not valid, a type in signature for example, and you are getting an error. > Look for errors in your payment details.

> When i check database i always have 2 entries in PaymentToken. Is it normal?
> Yes, that's expected.

have you checked your payment details? could you post it here?

**Comment by makasim** [comment]
Most likely you have same problem as https://github.com/Payum/PayumBundle/issues/44

**Comment by polantis** [comment]
Hello,

Thank you for your answer. In fact, i had some issues regarding the table columns' structure. It is now working for "offline".

Regarding paypalexpresscheckoutnvp, i have another issue: "Unknown cipher in list: TLSv1"

CRITICAL - Uncaught PHP Exception Buzz\Exception\RequestException: "Unknown cipher in list: TLSv1" at vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php line 29
Context: {"exception":"Object(Buzz\\Exception\\RequestException)"} 

How can i add this cipher?

Thank you

**Comment by polantis** [comment]
I have changed vendor\payum\payum-bundle\Resources\config\payum.xml. I have added a call to payum.buzz.client service and it is now working:

<call method="setOption">
                
                <argument>10083</argument>
                <argument>null</argument>
</call>

Should i change something else instead?

Thanks

**Comment by polantis** [comment]
< call method="setOption">
            
            < argument>10083< /argument>
            < argument>null< /argument>
< /call>
