### ISSUE TITLE
the document to use gateway via omnipay-bridge is not clear

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#298]
I look through all document about using gateway via omnipay-bridge, but I can't find a working example, such as  [Stripe via omnipay](https://github.com/Payum/PayumBundle/blob/master/Resources/doc/custom_purchase_examples/stripe_via_omnipay.md), I did exactly as it is,  it showed this error:

    Invalid configuration for path "payum.gateways.stripe.omnipay_direct": Given type Stripe is not supported. Try one of supported types: or use the gateway full class name.

what else steps should I do?

**Comment by makasim** [comment]
this works for me https://github.com/makasim/PayumBundleSandbox/blob/master/app/config/payum.yml#L169

**Comment by makasim** [comment]
have you installed omnipay/stripe package?

**Comment by makasim** [comment]
another doc which may be of use: http://payum.org/doc/1.0.0-BETA1/PayumBundle/custom_purchase_examples/stripe_via_omnipay

**Comment by videni** [comment]
@makasim , you are right , I didn't install that package
I am using a none official listed gateway  [labs7in0/omnipay-wechat](https://github.com/labs7in0/omnipay-wechat.git), I am tring to use that gateway as an example for this wechat gateway.

    stripe_via_omnipay:
            omnipay_direct:
                type: Stripe
                options:
                    apiKey:  %stripe.secret_key%
                    testMode: true

each supported gateway is listed  [here](https://github.com/thephpleague/omnipay/blob/master/composer.json), so setting gateway type name as Stripe is not possible,  I noticed that the type can be a full qualified   class name, I change these code as below:

     gateways:
        wechat:
            omnipay_direct:
                type:  Omnipay\WeChat\ExpressGateway
                options: ~

it is supposed to work,  but throwing this error:

>Given type Omnipay\WeChat\ExpressGateway is not supported. Try one of supported types: .

**Comment by makasim** [comment]
The exception is thrown from the omnipay code, I suppose it is not payum nor payum bridge issue, as the bridge correctly pass everything to omnipay side. 

Worth trying to add `\` at the beginning

**Comment by videni** [comment]
I try to user a another official listed gateway "Alipay Wap Express", the error is still the same
I think it is a error of ominipay common, I found these code 

Omnipay/Common/GatewayFactory.php

     foreach ($this->getSupportedGateways() as $gateway) {
            $class = Helper::getGatewayClassName($gateway);

            if (class_exists($class)) {
                $this->register($gateway);
            }
        


the getSupportedGateways will  fetch supported gateway from [composer.json](https://github.com/thephpleague/omnipay-common/blob/master/composer.json) file,as you can see , there is a space between  the gateway "Alipay Wap Express",   it will try to locate "\Omnipay\Alipay Wap Express\Gateway"  class, of course this class can not be found.

**Comment by makasim** [comment]
feel free to reopen

**Comment by MHaendel** [comment]
Exactly the same error. If I comment out this part in the OmnipayDirectGatewayFactory it works.

type is FQCN \Omnipay\Gateway\Paysafecard

```php
$supportedTypes = $gatewayFactory->all();
if (false == in_array($config['type'], $supportedTypes)) {
    throw new LogicException(sprintf(
        'Given type %s is not supported. Try one of supported types: %s.',
        $config['type'],
        implode(', ', $supportedTypes)
    ));
}	
```

**Comment by makasim** [comment]
It should not be commented out, instead there should be additional check like 


```
class_exists($config['type']) || in_array($config['type'], $supportedTypes)
```

**Comment by MHaendel** [comment]
```php
if (false == class_exists($config['type'])) {
    if(false == in_array($config['type'], $supportedTypes)){
        throw new LogicException(sprintf(
            'Given type %s is not supported. Try one of supported types: %s.',
            $config['type'],
            implode(', ', $supportedTypes)
        ));
    }
}
```

works with the expected behaviour. Can we expect an update? :+1:

**Comment by makasim** [comment]
Do a pull request

**Comment by MHaendel** [comment]
I just updated the package.
Seems it's fixed now :)
