### ISSUE TITLE
adding action to specific gateway  is not working

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#300]
I have a gateway like this : 

    gateways:
        wechat:
            omnipay_offsite:
                type:  \Omnipay\WeChat\ExpressGateway
                options: ~

then , I create a action and try to add this action to wechat gateway 

       <service id="vmsp_payment.payum.action.capture_payment_using_wechat" class="VMSP\PaymentBundle\Payum\Action\CapturePaymentUsingWechatAction">
            <tag name="payum.action"   gateway="wechat"  alias="wechat_payment_offsite" />
        </service>                  

I list all gateway configured to wechag using command  payum:gateway:debug, but there is no  CapturePaymentUsingWechatAction action,  

    wechat (Payum\Core\Gateway):
	Actions:
	Payum\OmnipayBridge\Action\OffsiteCaptureAction
	Payum\Core\Bridge\Symfony\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction
	Payum\Core\Bridge\Symfony\Action\ObtainCreditCardAction
	Payum\OmnipayBridge\Action\ConvertPaymentAction
	Payum\OmnipayBridge\Action\StatusAction

I change the tag for the action service to 

               <tag name="payum.action"   all="true" alias="wechat_payment_offsite" />

that action shows out,

It seems the `gateway="wechat"`   is not the only necessary  step, I found these code related to it

  Payum\Bundle\PayumBundle\GatewayFactory.php

     if (
                    isset($attributes['gateway']) &&
                    isset($config['payum.gateway_name']) &&
                    $config['payum.gateway_name'] === $attributes['gateway']
                ) {
                    $config["payum.action.$name"] = $this->container->get($id);
                }

somehow `$config['payum.gateway_name']` is alway null, anything I am missing?

**Comment by makasim** [comment]
most likely it is a bug

**Comment by makasim** [comment]
Works for me, try to remove cache before running payum:gateway:debug command.

**Comment by lunetics** [comment]
I think the DOC pages are not in sync gateways_v2:
see the container tags example(s) @

https://github.com/Payum/PayumBundle/blob/master/Resources/doc/custom_action_usage.md

and

https://github.com/Payum/PayumBundle/blob/master/Resources/doc/container_tags.md

especially the gateway parameter (old version?)
