### ISSUE TITLE
how can i render the card form

### ISSUE THREAD

**Issue by medy36** [Payum/PayumBundle#302]
in my prepare action i'm rendering the card form if form is not submitted, then i'm redirected to capture doAction with an other card form.

how can i use my card form instead of having to fill two card form?

    public function userIndividualFeeAction(Request $request) 
    {
        $user = $this->getUser();
        // get our gateway
        $paymentName = 'express';

        $form = $this->createPurchaseForm();
        $form->handleRequest($request);
        if ($form->isValid()) {

            $data = $form->getData();
            // payment entity
            $storage = $this->get('payum')->getStorage('NZW\Bundle\PaymentBundle\Entity\Payment');
            // instance order
            $order = $storage->create();
            $order->setDetails(array());
            $order->setNumber(uniqid());
            $order->setCurrencyCode('USD');
            $order->setTotalAmount(10.00);
            $order->setAmount(10.00); 
            $order->setDescription('Individual payment for search ($10)');
            $order->setClientId($this->getUser()->getId());
            $order->setUserId($this->getUser());
            $order->setClientEmail($this->getUser()->getEmail());

            $storage->update($order);

            $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
                    $paymentName, $order, 'nzw_search_individual_payment' // the route to redirect after capture
            );
            // var_dump($captureToken);
            return $this->redirect($captureToken->getTargetUrl());
             // return $this->forward('PayumBundle:Capture:do', array(
             //        'payum_token' => $captureToken,
             //    ));
        }

        // return $this->redirect($captureToken->getTargetUrl());
         return $this->render('NZWPaymentBundle:PurchaseOmnipay:prepare.html.twig', array(
            'form' => $form->createView()
        ));
    }

**Comment by makasim** [comment]
You cannot use redirect with credit card submitted in your action because of security reasons. The card details must not be stored at your side. Instead of redirect you have to try to use `forward` 


You can also work around it and force card saving.

**Comment by makasim** [comment]
like this https://github.com/makasim/PayumBundleSandbox/blob/00cbaf8e7b9b0aca63477ccc89fe82c701372b1a/src/Acme/PaymentBundle/Controller/SimplePurchaseStripeViaOmnipayController.php#L36

**Comment by medy36** [comment]
Thank you for your answer makasim!

when i use the forward i got a loop from 
return $this->render('NZWPaymentBundle:PurchaseOmnipay:prepare.html.twig', array(
        'form' => $form->createView()
    ));

to the capture doAction.

weird, it's now working for me using the redirection:

  public function userIndividualFeeAction(Request $request) 
    {
        $user = $this->getUser();
        // get our gateway
        $paymentName = 'express';

        $form = $this->createPurchaseIndividualForm();
        $form->handleRequest($request);
        if ($form->isValid()) {

            $data = $form->getData();           
            // $data['package'] set the price in business account

            // payment entity
            $storage = $this->get('payum')->getStorage('NZW\Bundle\PaymentBundle\Entity\Payment');
            // instance order
            $order = $storage->create();
            $order->setDetails(array());
            $order->setNumber(uniqid());
            $order->setCurrencyCode('USD');
            $order->setTotalAmount(10.00);
            $order->setAmount(10.00); 
            $order->setDescription('Individual payment for search ($10)');
            $order->setClientId($this->getUser()->getId());
            $order->setUserId($this->getUser());
            $order->setClientEmail($this->getUser()->getEmail());

            $storage->update($order);

            $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
                    $paymentName, $order, 'nzw_search_individual_payment' // the route to redirect after capture
            );

            return $this->redirect($captureToken->getTargetUrl());
            

        }

        // return $this->redirect($captureToken->getTargetUrl());
         return $this->render('NZWPaymentBundle:PurchaseOmnipay:prepare.html.twig', array(
            'form' => $form->createView()
        ));
    }


but i still stock in how to get the capture form (credit card) , i checked the structure of the core payum and i can't find a way to override it, or put my hand on it to style it or whatever.

**Comment by makasim** [comment]
What do you want to overwrite?

**Comment by medy36** [comment]
What i really want is when i'm redirected to the payment form page, which
is handled by the forward function, i would like to customize the payment
card form. all i can do now is overriding the Layout page of payum.

2015-10-24 21:12 GMT+01:00 Maksim Kotlyar <notifications@github.com>:

> What do you want to overwrite?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Payum/PayumBundle/issues/302#issuecomment-150847214>.
>



-- 
Cordialement,

*Lasri Mehdi*


*Tel: * *+212 655 18 28 16*
*Fax*: +212 *537 77 64 63*
lasri.mehdi@gmail.com <xxxxx@creativegroupe.com>

* 15, AVENUE AL ABTAL, APP.N°4, AGDAL*

**Comment by makasim** [comment]
you can overwrite the page template too, also you can overwrite the form type service.

**Comment by medy36** [comment]
thank you, i thiink the form service would be enough for now.

But can you please explain me how we can override form, actions coming from
the Core folder which is not in the payum-bundle.

2015-10-25 11:15 GMT+00:00 Maksim Kotlyar <notifications@github.com>:

> you can overwrite the page template too, also you can overwrite the form
> type service.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Payum/PayumBundle/issues/302#issuecomment-150912730>.
>



-- 
Cordialement,

*Lasri Mehdi*


*Tel: * *+212 655 18 28 16*
*Fax*: +212 *537 77 64 63*
lasri.mehdi@gmail.com <xxxxx@creativegroupe.com>

* 15, AVENUE AL ABTAL, APP.N°4, AGDAL*

**Comment by medy36** [comment]
Hi Maksim,

Im getting back to you again regarding some configurations. i need to
enable  EnableAddBillCard
<http://www.paymentexpress.com/technical_resources/ecommerce_nonhosted/pxpost.html#EnableAddBillCard>(Set
to true when adding a card) so i can get the user token.

i can't find where to inject that!

please i need to commit tonight and tomorrow is the died line. Thanks in
advance.

2015-10-25 11:18 GMT+00:00 Mehdi Lasri <lasri.mehdi@gmail.com>:

> thank you, i thiink the form service would be enough for now.
>
> But can you please explain me how we can override form, actions coming
> from the Core folder which is not in the payum-bundle.
>
> 2015-10-25 11:15 GMT+00:00 Maksim Kotlyar <notifications@github.com>:
>
>> you can overwrite the page template too, also you can overwrite the form
>> type service.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Payum/PayumBundle/issues/302#issuecomment-150912730>.
>>
>
>
>
> --
> Cordialement,
>
> *Lasri Mehdi*
>
>
> *Tel: * *+212 655 18 28 16*
> *Fax*: +212 *537 77 64 63*
> lasri.mehdi@gmail.com <xxxxx@creativegroupe.com>
>
> * 15, AVENUE AL ABTAL, APP.N°4, AGDAL*
>
>
>
>
>
>
>



-- 
Cordialement,

*Lasri Mehdi*


*Tel: * *+212 655 18 28 16*
*Fax*: +212 *537 77 64 63*
lasri.mehdi@gmail.com <xxxxx@creativegroupe.com>

* 15, AVENUE AL ABTAL, APP.N°4, AGDAL*

**Comment by makasim** [comment]
@medy36 Hi, Are you using an omnipay gateway? If so the answer is I dont know how to pass custom parameters via omnipay gateway.

**Comment by makasim** [comment]
Ask the question at paypal express omnipay repository.
