### ISSUE TITLE
events dispatching/model update

### ISSUE THREAD

**Issue by toooni** [Payum/PayumBundle#304]
I wonder why the approach is to change the model or dispatch an event into the done action. Wouldn’t it be better to dispatch an event inside the notify action? Can't it be that a notify request was made and the user did close the window or changed (f.e.) to the paypal account without returning to the done action. In this case the model would not be updated.
Maybe I missed something.. ?

**Comment by makasim** [comment]
The doc shows the simplest example, not all gateway have a notifications. Here you can find an extension which updates model, whenever it is a done page or notification request. 

http://payum.org/doc/1.0/Core/instant-payment-notification

**Comment by toooni** [comment]
@makasim thank you for the fast answer.. this was exactely what i was looking for. it took me some time to dig into this bundle/library but i think it's worth it! nice work!

**Comment by toooni** [comment]
@makasim one last question, sorry.. how do i get the storage from the context in onPostExecute?

**Comment by makasim** [comment]
You cannot, you have to inject it yourself, via constructor. all storages (which you configured) are services in container. you can easily find them with `container:debug | grep payum` command.

**Comment by toooni** [comment]
thank you!

**Comment by toooni** [comment]
btw. souldn't it be `if ($request instanceof GetStatusInterface) {` in http://payum.org/doc/1.0/Core/instant-payment-notification instead of `if (false == $request instanceof GetStatusInterface) {`?

Else it's going in an endless-loop. Should i make a PR?
