### ISSUE TITLE
Urgent need to Enable Add Bil lCard

### ISSUE THREAD

**Issue by medy36** [Payum/PayumBundle#305]
Hello,

i'm coming back again regarding this issue, i need to activate EnableAddBillCard for ExpressPayment to get the cardReference of the card holder, so later we can make renewals their subscriptions automatically.

Please i really need to fix this ASAP. Thank you!

**Comment by makasim** [comment]
What exactly do you want from me?

**Comment by makasim** [comment]
Pass required details to paypal, as their doc suggest. Does it work for you?

**Comment by medy36** [comment]
i finish by overriding the omnipay API to enable recurring billing. thank
you for your time

2015-11-13 10:52 GMT+00:00 Maksim Kotlyar <notifications@github.com>:

> Pass required details to paypal, as their doc suggest. Does it work for
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Payum/PayumBundle/issues/305#issuecomment-156395867>.
>



-- 
Cordialement,

*Lasri Mehdi*


*Tel: * *+212 655 18 28 16*
*Fax*: +212 *537 77 64 63*
lasri.mehdi@gmail.com <xxxxx@creativegroupe.com>

* 15, AVENUE AL ABTAL, APP.N°4, AGDAL*
