### ISSUE TITLE
Where do addApis go?

### ISSUE THREAD

**Issue by kayue** [Payum/PayumBundle#306]
I am trying to upgrade to 0.14, and I found that `addApis` in PaymentFactory is no longer being used...

https://github.com/Payum/PayumBundle/commit/185be60062f406359216f61b5320fc61104b1dca#diff-d83ec829930974b5570064c53f84a0d2L22

May I know what is the replacement of this? 

Also I used to rely on the `payum.context.$contextName.api` service, because I need access to the the actual API. For example, my Braintree integration need to use `payum.context.braintree.api` to generate token for its JS form

```php
protected function addApis(Definition $paymentDefinition, ContainerBuilder $container, $contextName, array $config)
{
    $apiDefinition = new DefinitionDecorator('store.braintree.api');
    $apiDefinition->replaceArgument(0, $config['options']);
    $apiDefinition->setPublic(true);
    $apiId = 'payum.context.'.$contextName.'.api';
    $container->setDefinition($apiId, $apiDefinition);
    $paymentDefinition->addMethodCall('addApi', [new Reference($apiId)]);
}
```

Thanks a lot.

**Comment by makasim** [comment]
The api is created in a factory from payum lib, not payum bundle. The options is prepared and passed to that factory. PayumBuildle factory does not build the gateway any more.

If you want to overwrite the api do next: Create an api service and add a tag to it `payum.api` with an alias `payum.api`. Let me know if this does not work.

**Comment by kayue** [comment]
@makasim Thanks for the information. I built an action to get the api from the gateway.

```php
$apiRequest = new GetApiRequest();
$this->braintreeGateway->execute($apiRequest);

return $apiRequest->getApi()->getClientToken();
```

**Comment by makasim** [comment]
Hm, maybe it is better to add an actoin\request which gets the token?

**Comment by kayue** [comment]
@makasim Actually since I need to access the payment gateway in a Twig extension, and payment gateway also require twig (`twig.env`),  this will create a circular reference `payum.braintree.braintree.payment -> payum.braintree.factory -> twig -> store.twig.payment_extension`

**Comment by makasim** [comment]
Pass a container to twig extension.

**Comment by makasim** [comment]
You can render a template inside payum for example https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/Action/Api/ObtainTokenAction.php#L70

Can I see a code somewhere?

**Comment by kayue** [comment]
It is a closed source private project. 

We are using Sylius, but we didn't use the default integration because it required a separated page to handle payment (credit card form page), but it isn't ideal in UX aspect. We want a single-page checkout, thus we need to use Twig extension to render the token.

I solved this by removing twig from the factory parameter, it isn't required in my case, but yes passing a container to twig extension would solve the problem too.
