### ISSUE TITLE
NotifyController response code 200 instead of 204?

### ISSUE THREAD

**Issue by toooni** [Payum/PayumBundle#307]
I am creating a new Payment-Gateway "https://github.com/invit/payum-sofortueberweisung" which implements the usage of Sofortueberweisung (At the moment just for Version 0.15 because i cannot update because of other dependencies).
Unfortunately Sofort does not accept the response code 204 to their notifications. They just retry to notify until the answer is a 200 status code. Is there a specific reason to use a 204 response (another payment provider?) or might it be ok to change this in the bundle?

If there's no chance that this can be changed, what would you recommend to do?

**Comment by makasim** [comment]
The 204 is a default behavior, of course you can change it. You have throw a http response reply with what you need. This is how I did it in Be2Bill notify action: https://github.com/Payum/Payum/blob/master/src/Payum/Be2Bill/Action/NotifyAction.php#L56

**Comment by toooni** [comment]
Oh, Thank you.. Now my question looks pretty stupid to me :)
