### ISSUE TITLE
Cancel Recurring Payment error 1048576

### ISSUE THREAD

**Issue by vazgen** [Payum/PayumBundle#313]
Hello,

I get an error (status code **1048576**) when I want to cancel Recurring Payment (I use paypal).  I did not find description of this error at https://developer.paypal.com/docs/classic/api/errorcodes/. 

**version of bundles:**
   payum/payum 0.6.3
   payum/payum-bundle 0.6.2
   payum/paypal-express-checkout-nvp 0.6.4

**Comment by makasim** [comment]
The 0.6.x version is two  **years** old and is no longer supported. Try out the newer versions, ideally 1.0.

Regarding the error, I've never seen such errors or similar one.
