### ISSUE TITLE
Override HttpRequestVerifier

### ISSUE THREAD

**Issue by MHaendel** [Payum/PayumBundle#315]
Hi, is there any way to override the default HttpRequestVerifier?
I run Angular as frontend, passing the payum_token via api.

Following Error: 
```json
{
  "code": 400,
  "message": "The current url http:\/\/project.dev\/app_dev.php\/api\/v1\/payment\/deposit\/done?payum_token=AhlA2WyFbSXVVieGFzMPOV18rPFhggvbNl3KIHtHuag not match target url http:\/\/localhost:3000\/dashboard-project?payum_token=AhlA2WyFbSXVVieGFzMPOV18rPFhggvbNl3KIHtHuag set in the token."
}
```

is there any other way doing this?

**Comment by makasim** [comment]
It is an ordinary symfony service, you can overwrite it as any other services. 

Just register a service with the name `payum.security.http_request_verifier`.

https://github.com/Payum/PayumBundle/blob/master/Resources/config/security.xml#L18
