### ISSUE TITLE
Symfony bundle and Paypal REST API

### ISSUE THREAD

**Issue by acanimal** [Payum/PayumBundle#317]
Hi, I'm using symfony and want to user Paypal REST. Why Paypal REST API is not integrated with payum-bundle (symfony)?
and what are the steps to integrate it?

**Comment by makasim** [comment]
I dont use it, and nobody else was able to contribute the support. Should not be hard to add. You just have to create a factory like this https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/Factory/Gateway/PaypalExpressCheckoutNvpGatewayFactory.php and register it in the bundle like this: https://github.com/Payum/PayumBundle/blob/master/PayumBundle.php#L39

**Comment by makasim** [comment]
Would you like to work on it?

**Comment by makasim** [comment]
P.S. The Paypal REST extension needs some love too

**Comment by acanimal** [comment]
I'll do my best but don't if it will be enough :)
