### ISSUE TITLE
Refund with PayumBundle

### ISSUE THREAD

**Issue by acanimal** [Payum/PayumBundle#320]
Hi,
I'm using PayumBundle with Paypal Express Checkout gateway. I'm trying to implement refund action as explained here (http://payum.org/doc/1.0/PayumBundle/refund) but I get an error saying the maybe the gateway does not implements refund or it can be a bug?

My code is:

```php
    /**
     * @Route("/refund", name = "komik_payment_refund")
     */
    public function refundAction(Request $request)
    {
        $gateway = $this->get('payum')->getGateway('paypal_express_checkout');

        $number = '567d9528a8418';
        $storage = $this->get('payum')->getStorage('Acme\AppBundle\Entity\Payment');
        $payment = $storage->findBy(array('number' => $number));

        $gateway->execute(new Refund($payment));
        $gateway->execute($status = new GetHumanStatus($payment));

        if ($status->isRefunded()) {
          echo "Refund done !!";
        } else {
          // Something went wrong. Lets check details to find out why

          var_dump($payment->getDetails());
        }
    }
```

Any help on making refund works will be appreciated.

**Comment by makasim** [comment]
Paypal Express Checkout refund action has not been implemented. This an action of paypal pro: https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ProCheckout/Nvp/Action/RefundAction.php

**Comment by acanimal** [comment]
Any idea to add it to express checkout nvp?  At least the paypal API seems to support it?
Thanks.

**Comment by makasim** [comment]
Yes, Paypal indeed supports it, and Payum supports it too. It has to be implemented, and it is pretty easy to do.

**Comment by acanimal** [comment]
Yep, I just cloned payum repository and looking on express checkout nap extension but I'm relatively new to Symfony and much more to payum framework. I'll try :)

**Comment by g0ld3lux** [comment]
do you have a sample on how to listen to paypal when the user cancel recurring payment in their back office? im currently using paypal_express_pro .... Do i also need to install paypal ipn...
If so how can i do it... do you have a stub sample i can study and implement with laravel thanks

**Comment by makasim** [comment]
You have to develop and register an extension which contains your business logic. here's an example https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/instant-payment-notification.md

**Comment by g0ld3lux** [comment]
can you explain this part? is this Ok to be null , what are the use cases of that 2 method
```
 public function onPreExecute(Context $context)
    {
    }

    /**
     * {@inheritDoc}
     */
    public function onExecute(Context $context)
    {
    }
```

**Comment by g0ld3lux** [comment]
so basically i can do something like this
routes.php
```
Route::any('paypal/ipn/','PaypalController@onPostExecute');
```
then in PaypalController
```
public function onPostExecute(Context $context)
    {
        $request = $context->getRequest();
        if (false == $request instanceof Generic) {
            return;
        }
        if ($request instanceof GetStatusInterface) {
            return;
        }

        $payment = $request->getModel();
        if (false == $payment instanceof PaymentInterface) {
            return;
        }

        $context->getGateway()->execute($status = new GetHumanStatus($payment));

        // check the status and act accordingly
       // HERE I ADD MY LOGIC 
       // Cancel Subscription
    }
```

**Comment by makasim** [comment]
No, you cannot do it that way. It will never work. This an extensino for payum gateway and you have to register your extension (a separate class) to the gateway.

**Comment by g0ld3lux** [comment]
so i will composer require payum/paypal-ipn  to have it...
as i read the doc, it says i dont need to do anything as long as the notify url is accessible from web
i did php artisan route:list
i have this route
```
GET|HEAD|POST|PUT|PATCH|DELETE | payment/notify/{payumToken}                                                                   | payment.notify
```
this one i think would be the link to receive the notification...
then 
as you said now i need to create a separate class... ?
if i have created that class where would i new it up ?
please advice thanks

**Comment by g0ld3lux** [comment]
i actually have this class its on the vendor
```
<?php

namespace Recca0120\LaravelPayum\Extension;

use Payum\Core\Extension\Context;
use Payum\Core\Extension\ExtensionInterface;
use Payum\Core\Model\PaymentInterface;
use Payum\Core\Request\Generic;
use Payum\Core\Request\GetHumanStatus;
use Payum\Core\Request\GetStatusInterface;
use Illuminate\Contracts\Events\Dispatcher;
use Recca0120\LaravelPayum\Event\StatusChanged;

class UpdatePaymentStatusExtension implements ExtensionInterface
{
    protected $events;

    public function __construct(Dispatcher $events)
    {
        $this->events = $events;
    }

    /**
     * {@inheritdoc}
     */
    public function onPreExecute(Context $context)
    {
    }

    /**
     * {@inheritdoc}
     */
    public function onExecute(Context $context)
    {
    }

    /**
     * {@inheritdoc}
     */
    public function onPostExecute(Context $context)
    {
        if ($context->getPrevious()) {
            return;
        }
        /** @var Generic $request */
        $request = $context->getRequest();

        if (false == $request instanceof Generic || $request instanceof GetStatusInterface) {
            return;
        }

        $payment = $request->getFirstModel();
        if ($payment instanceof PaymentInterface) {
            /* @var Payment $payment */
            $status = new GetHumanStatus($payment);
            $context->getGateway()->execute($status);
            $this->events->fire(new StatusChanged($status));

            if (method_exists($payment, 'setStatus') === true) {
                $payment->setStatus($status->getValue());
            }
        }
    }
}

```
where can i use this then? controller? model? sorry im bit confuse , i really cant find example in docs... thanks for reply

**Comment by makasim** [comment]
add it here https://github.com/Payum/Payum/blob/master/src/Payum/Core/Gateway.php#L80

**Comment by g0ld3lux** [comment]
i already have PaymentStatusExtension class ...
but its the plain one... i would create a new class and extend it ... and add my logic after this line.

```
//  MyPaymentStatusExtension.php
$context->getGateway()->execute($status = new GetHumanStatus($payment));
 // check the status and act accordingly
```'
After i do that ill create a method in my controller 
```
// PaypalController.php
use MyPaymentStatusExtension;
public function listenIPN(PayumService $payumService, Request $request, $payumToken)
{
return $payumService->addExtension( MyPaymentStatusExtension $extension);
}
```
then add it in route
```
Route::any('ipnlistener', 'Paypalcontroller@listenIPN');
```
Is this the right way of doing it? please advise thanks

**Comment by tghelios** [comment]
is refund for paypal express checkout implemented?

**Comment by makasim** [comment]
@tghelios nope, it hasn't been implemented

**Comment by jimiero** [comment]
@makasim has this been implemented?

**Comment by makasim** [comment]
no, it's not.

**Comment by jimiero** [comment]
@makasim thanks, can you list here or provide a link with all gateways supporting refund?

**Comment by makasim** [comment]
just search in Payum repo for `RefundAction` or `RefundRequest`
