### ISSUE TITLE
Paypal Void Action

### ISSUE THREAD

**Issue by nexxome** [Payum/PayumBundle#324]
Hi,
can someone give me a hint how to make a Void Action request for Paypal NVP using PayumBundle?
https://developer.paypal.com/docs/classic/api/merchant/DoVoid_API_Operation_NVP/

**Comment by makasim** [comment]
It is not implemented. We must add an action which support cancel (void in terms of Paypal) request: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Request/Cancel.php
