### ISSUE TITLE
Overriding Payum Stripe Bundle templates

### ISSUE THREAD

**Issue by clytemnestra** [Payum/PayumBundle#326]
I'm trying to customise the templates of StripeBundle, respectively the checkout template vendor\payum\stripe\Payum\Stripe\Resources\views\Action\obtain_checkout_token.html.twig.

This is because I want the Stripe popup to appear in the same page as the object that is paid for and not on a separate page with a single button. Say, I want to pay for a Product, I press 'pay' at the checkout page, and want the Stripe popup to appear there.

I took a look at [another similar question](http://stackoverflow.com/questions/24858961/payum-bundle-how-to-change-the-view-of-capture-action-in-symfony2/24859255#24859255) but I can't seem to get it working. I've tried every single combination of folder names in app/Resources with PayumStripeBundle, Payum, Payum/Stripe, but none of them seem to override the used template.

The bundle's structure is also pretty strange, as its namespace is Payum\Bundle\PayumBundle, but the Stripe component which is not a bundle that contains the template is in another folder.

The value is set [here](https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/Factory/Gateway/StripeCheckoutGatewayFactory.php#L53), so maybe Symfony never looks in the folder because of that?

How should the folder structure in app/Resources be, if it works this way? Or if it's another way to do it.

In the meantime, I believe those routes/controllers are 'forcing' us to use them, so we need to create other routes to use.

I believe it's something similar to [this issue](https://github.com/Payum/PayumBundle/issues/270) but I can't get it to work properly.

```php
    public function prepareAction(Request $request)
    {

        $currency = "USD";
        $amount = 100;

        $gatewayName = 'stripe';
        $storage = $this->get('payum')->getStorage('ParkResortBundle\Entity\Payment');

        /** @var Payment $payment */
        $payment = $storage->create();
        $payment->setCurrencyCode($currency);
        $payment->setTotalAmount($amount);
        $payment->setDescription($amount . $currency);

        if ($request->isMethod('POST') && $request->request->get('stripeToken')) {

            // $payment->setCreditCard($request->request->get('stripeToken'));
            $storage->update($payment);

            $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
                $gatewayName,
                $payment,
                "park_resort_pay_done"
            );




            return $this->redirect($captureToken->getTargetUrl());
        }

        return $this->render('@ParkResort/Pages/test.html.twig', array(
            'currency' => $currency,
            'totalAmount' => $payment->getTotalAmount(),
            'publishable_key' => $this->container->getParameter('stripe_public_key'),
            'payment' => $payment,
            'gatewayName' => $gatewayName
        ));
    }

```

This creates the form, in my custom page, but after submitting it, I am redirected to the /capture/token route and have to fill the original stripe form again. Somehow I need to validate the payment by filling the details and capture the token without ```createCaptureToken()``` function sending me there, because that function is the one rendering the payment forms for the tokens.

I made it work like so

```php
     if ($request->isMethod('POST') && $request->request->get('stripeToken')) {

            $this->get('payum')->getGateway('stripe')->execute(new Capture($payment));
        
        }
```

This does create a payment object, it fills the details and I see it on the Stripe website payments on my account, however this doesn't create tokens to be captured, and I'm not sure how safe&secure it is. I'd like suggestions, please.

**Comment by makasim** [comment]
There are container parameters, by customizing them you can change the template to one you need.

**Comment by clytemnestra** [comment]
But to add custom data in the view, the captureAction needs to be overridden. Is that a good idea if I want to show in the capture view details of the object that is paid for?

**Comment by makasim** [comment]
The model has to be passed to the template. https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/Action/Api/ObtainTokenAction.php#L71
