### ISSUE TITLE
Paypal Payment Pro

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#329]
Hi There,

Is it possible to use a custom form on the paypal payment pro extension to process the card details so this can be done on the same page? If not is it possible to override the form template so we can modify the form? I can't seem to see anything in the documentation about overriding the form and the only method I can think of is using the capture function code inside of the prepare function to process and skip this. If you could advise that would be great.

**Comment by makasim** [comment]
It is possible to overwrite templates and it is possible to process the form at the same page as long as you do not store credit card details anywhere, hence you cannot use redirect.

**Comment by liamsorsby** [comment]
@makasim is there any documentation on processing the form on the same page or is it a case of using the processing code and not redirecting as in the original code to the capture script?

**Comment by makasim** [comment]
The idea is to use `forward` instead of redirect, like this https://github.com/makasim/PayumBundleSandbox/blob/cd296496881680608d4e51e293d49afc71f75bbd/src/Acme/PaymentBundle/Controller/SimplePurchasePaypalProController.php#L38

The template could be overwrite via the container parameter.

**Comment by liamsorsby** [comment]
@makasim thats great thank you. unfortunately, the documentation contradicts itself. We are trying to add the cvv2 ect to the array but we are getting an unable to access object as an array. I've taken a look at the documentation for version 1.0 on both the following docs: http://payum.org/doc/1.0/PayumBundle/get_it_started and http://payum.org/doc/1.0/PayumBundle/storages if you take a look at the Payment entities on both of these one of them will extend BasePayment and the other extends ArrayObject. Which one of them are correct?

**Comment by makasim** [comment]
Both variants correct, even more you can use your own object as long as you provide convert (to array) action. array is structure is the base payment model is converted to it (under the hood). 

It is up to you what to use.

**Comment by liamsorsby** [comment]
@makasim we have used the following:

`<?php
namespace Acme\PaymentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\Payment as BasePayment;

/**
 * @ORM\Table
 * @ORM\Entity
 */
class Payment extends BasePayment
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer $id
     */
    protected $id;
}`

but unfortunately when using this method and the following code:

`
$payment["cvv2] = new SensitiveValue(123412341234);
`

Throws the error: cannot use object of type .... Entity/Payment as array we are using version 1.0.1 of PayumBundle is there something that we're missing?

**Comment by makasim** [comment]
Something like this must work:

```php
<?php
$payment->setDetails(['cvv2' => new SensitiveValue(123412341234)]);
```

**Comment by makasim** [comment]
Seems like paypal pro [convert action](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ProCheckout/Nvp/Action/ConvertPaymentAction.php#L29) does not support conversion of credit cards yet.

Must be something like this: https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/Action/ConvertPaymentAction.php#L30

**Comment by liamsorsby** [comment]
@makasim I've had a play about and it seems that paypal pro only works on the ArrayObject version of the entity and not on the other entity when your wanting to use the card processor on the same page.

**Comment by makasim** [comment]
It hast to, there is not any limitations and I am pretty sure it works.

if it is not than it has to be fixed.
