### ISSUE TITLE
Compatibility with symfony3

### ISSUE THREAD

**Issue by LazyDreamer22** [Payum/PayumBundle#330]
Any expectation when this bunle will be compatible with symfony3 ??

**Comment by LazyDreamer22** [comment]
as i got these msgs when trying to install the bundle via composer :

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.0.1
    - Conclusion: don't install symfony/symfony v3.0.1
    - payum/payum-bundle 1.0.0 requires symfony/form ~2.7 -> satisfiable by symfony/form[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - payum/payum-bundle 1.0.1 requires symfony/form ~2.7 -> satisfiable by symfony/form[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - payum/payum-bundle 1.0.2 requires symfony/form ~2.7 -> satisfiable by symfony/form[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - payum/payum-bundle 1.0.3 requires symfony/form ~2.7 -> satisfiable by symfony/form[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - don't install symfony/form v2.7.0|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.1|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.2|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.3|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.4|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.5|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.6|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.7|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.8|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.7.9|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.8.0|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.8.1|don't install symfony/symfony v3.0.1
    - don't install symfony/form v2.8.2|don't install symfony/symfony v3.0.1
    - Installation request for symfony/symfony == 3.0.1.0 -> satisfiable by symfony/symfony[v3.0.1].
    - Installation request for payum/payum-bundle ^1.0 -> satisfiable by payum/payum-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3].


Installation failed, reverting ./composer.json to its original content.

**Comment by makasim** [comment]
current master (It will be 1.2.0 release) supports symfony 3.0 and php7. Though it may contain some bugs. I am welcome you to test it.

**Comment by makasim** [comment]
You have to use versions: `payum/payum: 1.2@dev` and `payum/payum-bundle: 1.2@dev`.
