### ISSUE TITLE
Paypal Payment Pro Name not specified

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#341]
@makasim Is it possible to set the user's name on the PaypalProCheckoutNvp? When we make a payment it comes through as not provided even though it is provided in the payment_details model.

If not, is this a feature that could be added?

**Comment by makasim** [comment]
Not sure I get what you are talking about. Could explain it in more details please?

**Comment by liamsorsby** [comment]
No Problem. When you create a capture payment using PaypalProCheckoutNvp. You send the card details, the amount and currency.

When you use Paypal Express you send the user details aswel.

So when you send a payment through PaypalProCheckoutNvp and have a look on the paypal dashboard it should show you the payment along with the name of the customer the payment is from. But with PaypalProCheckoutNvp it shows not provided in place of their name. As the details their name ect isn't passed through.

**Comment by makasim** [comment]
Still do not understand.

**Comment by liamsorsby** [comment]
I've attached an image of a payment recieved via the PaypalPro Checkout. As you can see the name isn't passed through.

![no-name](https://cloud.githubusercontent.com/assets/5270149/13326991/f967066e-dbdf-11e5-941c-064cf3679206.jpg)

**Comment by liamsorsby** [comment]
It would have been easier for me to ask how do you set the customer name on PaypalProCheckoutNvp or if it is possible.

For instance, would the following set the customer name?
```php
$paymentDetails["name"] = $first . " " . $last;
```

**Comment by makasim** [comment]
you can put whatever paypal pro support to the details. check their docs out.

https://developer.paypal.com/docs/classic/payflow/integration-guide/

**Comment by makasim** [comment]
Feel free to reopen
