### ISSUE TITLE
how to register an instance of  Payum\Core\GatewayFactory to PayumBundle?

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#343]
I have created a custom GatewayFactory , but I don't know how to register this factory to PayumBundle, 
as [this document](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/develop-gateway-with-payum.md) says , we need to add  that GatewayFactory to PayumBuilder

> use Payum\Core\PayumBuilder;
> 
> $defaultConfig = [];
> 
> $payum = (new PayumBuilder)
>     ->addGatewayFactory('paypal', new \Acme\Paypal\PaypalGatewayFactory($defaultConfig))
>     ->addGateway('paypal', [
>         'factory' => 'paypal',
>         'sandbox' => true,
>     ])
> 
>     ->getPayum()
> ;

PayumBundle has defined lots of AbstractGatewayFactory  which are used to register the official gateways, but I don't find document about how to register our custom GatewayFactory.  I think if PayumBuilder is a service , then I can write a compile pass to do this jobs, but it isn't . PayumBundle just don't follow my instinct of symfony.

**Comment by videni** [comment]
I found out later ， we can register a gateway with following steps:

### step 1

create  an gateway as[ this document](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/develop-gateway-with-payum.md)


### step2 

register the gateway

```
amespace Acme\ExampleBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;use 
use Acme\ExampleBundle\DependencyInjection\Factory\Gateway\PostalGatewayFactory;


class AcmeExampleBundle extends Bundle
{

    public function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new FormErrorHandlerCompilePass());
        $container->addCompilerPass(new AddressValidationGroupCompilePass());

        $extension = $container->getExtension('payum');

        $extension->addGatewayFactory(new PostalGatewayFactory());

    }


}
```

**Comment by makasim** [comment]
@videni yes this is how it works in 1.x version. I'd suggest you to use 2.x version. This is how you can do it there 

https://github.com/makasim/PayumBundleSandbox/blob/master/app/config/payum.yml#L194
