### ISSUE TITLE
Add document to show how to create a custom gateway?

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#344]
Although developing custom gateway seems to be the responsibility of Payum library,   I suggest PayumBundle make a living example to link them together. the document should cover this topic: 

1.  How to use Ominipay gateway in PayumBundle
2.  How to create gateway with Payum way and use that gateway in PayumBundle

**Comment by makasim** [comment]
I welcome you to contribute to the project by adding those docs.
