### ISSUE TITLE
[1.2.x] GetHttpRequestAction and ObtainCreditCardAction doesn't work for Symfony 3

### ISSUE THREAD

**Issue by BoShurik** [Payum/PayumBundle#346]
The reason is, that service "request" doesn't exist in Symfony 3 anymore

**Comment by makasim** [comment]
I see, not sure why tests did not catch it. Thanks for letting me know, are you working on the fix?

**Comment by BoShurik** [comment]
I don't really know, how to fix this. Inject request_stack? But in this case we must implement it in core.

**Comment by makasim** [comment]
Yes it has to be fixed in core

**Comment by BoShurik** [comment]
I'll make PR
