### ISSUE TITLE
how to use Payum way to write a gateway for API?

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#348]
It seems the payment flow of Payum is not suitable for API ,  as there is a  token generated at the prepare step, typically ,  when customer tries to purchase a order  using API, it should go into capture step directly.  I spend a few days on using Payum  ways to write a gateway for mobile,  there are lots of troubles showed out, can  anyone point me the right direction?

**Comment by makasim** [comment]
I did use Payum on several projects where payment is done via API. It is possible. The PayumServer expose an api to process payment. You can look at how it is designed.


Could you give more information about your context. I'll try to help you

**Comment by tumbochka** [comment]
I also used Payum on API i.e. a frontend app worked with a backend app via ajax requests. A pay workflow was:
1. The frontend app send POST to the backend app.
a) If paying with be2bill (credit card) the frontend app sent card details and the backend controller performed the payment via payum and returned the payment status.
b) If paying with paypal the frontend app sent a redirect url pointing to a frontend landing page
(continuing with option b)
2. The backend controller returned the paypal redirect url.
3. The frontend app redirected the user to paypal.
4.The user entered his paypal credentials and approved the payment.
5. Then the user redirected to the landing frontend url provided at point b, the invoice status is updated automatically.

**Comment by videni** [comment]
@makasim,   we are writing a payment gateway for a bank, right now , the bank exposes their API as socket,  we want to transform this to http API which is simpler to use.  we don't want to design this from scratch,  we have two jobs to do: 

1. implement the payment gateway for the bank
2.  the payment should work with other gateways like stripe, papal, we are going to use these payment methods in our mobile e-commerce app.

 the PayumBundle looks like what we want, but it is hard to simply it for API invoking.

**Comment by videni** [comment]
@tumbochka, do you use paypal   in a embedded web browser  in mobile  app ?

**Comment by makasim** [comment]
> implement the payment gateway for the bank

The payum works on a client side an interactants  with a gateway way. It was not designed to build a gateway itself. Though you can use it as a proxy between real gateways like paypal or stripe and your client. 

> the payment should work with other gateways like stripe, papal, we are going to use these payment methods in our mobile e-commerce app.

that's possible
