### ISSUE TITLE
[Symf 2.8] Configuration missing API declaration Paypal express checkout

### ISSUE THREAD

**Issue by Narkolapin** [Payum/PayumBundle#356]
Hi every one, 

My Symfony 2.8 throw an exception during the Peyum 's service call (`$storage = $this->get('payum')`).

> Type error: Argument 3 passed to Payum\Paypal\ExpressCheckout\Nvp\Api::__construct() must be an instance of Http\Message\MessageFactory, null given, called in C:\Dev\aha-project\vendor\payum\paypal-express-checkout-nvp\Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory.php on line 89 

> at Api ->__construct (array('username' => 'xxx', 'password' => 'xxx', 'signature' => 'xxx', 'sandbox' => true), object(HttpClient), null)
in vendor\payum\paypal-express-checkout-nvp\Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory.php at line 89

In the **PaypalExpressCheckoutGatewayFactory** class, you instanciate the **API** class with services parameters. But the `'httplug.message_factory'` service seems to be not found in my application.

`
//ayum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory 
return new Api($paypalConfig, $config['payum.http_client'], $config['httplug.message_factory']);
`

I think i have an package 's dependency error but i am not able to solve it. Here is my composer.json

`
"require": {

        "payum/payum-bundle": "^2.0",
        "payum/offline": "^1.3",
        "payum/paypal-express-checkout-nvp": "^1.3",
        "php-http/guzzle6-adapter": "^1.0",
        "php-http/httplug": "^1.0"
    },
`

Thank for your attention for my problem.

**Comment by makasim** [comment]
Make sure you have payum/core at least 1.3 version.
