### ISSUE TITLE
Invalid status marked

### ISSUE THREAD

**Issue by battle-art** [Payum/PayumBundle#360]
Hello,
I've been trying to set up PayumBundle with PayPal Express Checkout, everything seems fine and I've been testing different cases in paypal sandbox.
I have 2 sandbox accounts, personal and business, both of them have option "Payment Review" turned on.
And when I make payment status is set to "captured", while it should be "pending". If I login into merchants account the status there says "Under Review" (but in client's account status is "Completed"), and here are some of the payment details returned from request:
```
[CHECKOUTSTATUS] => PaymentActionCompleted
[PAYMENTINFO_0_PAYMENTSTATUS] => Pending
[PAYMENTINFO_0_PENDINGREASON] => paymentreview
[PAYMENTREQUEST_0_PAYMENTSTATUS] => Completed
[PAYMENTREQUEST_0_PENDINGREASON] => None
```

I am creating payment just like in the [documentation](https://github.com/Payum/PayumBundle/blob/master/Resources/doc/purchase_done_action.md)
```php
$captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
	$gatewayName,
	$details,
	'test_payment_done_paypal_express'
);
return $this->redirect($captureToken->getTargetUrl());
```

```php
$token = $this->get('payum')->getHttpRequestVerifier()->verify($request);
$gateway = $this->get('payum')->getGateway($token->getGatewayName());
$gateway->execute($status = new GetHumanStatus($token));
```

**Comment by makasim** [comment]
Thanks for reporting this, Looks like a bug. Are you going to try to fix it?

**Comment by battle-art** [comment]
Unfortunately, I don't have much time at the moment. I could try to fix it, but it'll be a while before I'll look into it.

**Comment by makasim** [comment]
I've just merged the fix to master @battle-art could you try it out?

**Comment by battle-art** [comment]
It didn't fix the problem

**Comment by makasim** [comment]
than we need an extra fix.
