### ISSUE TITLE
Payum with Sonata Admin not work

### ISSUE THREAD

**Issue by muspelheim** [Payum/PayumBundle#361]
Hi, I have issue with sonata admin

after install payum bundle and configure, I have error:
Could not load type "payum_gateway_config"

any idea to fix it?

**Comment by makasim** [comment]
payum_gateway_config  [here](https://github.com/Payum/PayumBundle/blob/ab9c8b77c99570e98126ebe31757ad4f0e87104e/Sonata/GatewayConfigAdmin.php#L55) has to be changed to PayumGatewayType::class or something like this. (It is a change in symfony forms)

**Comment by muspelheim** [comment]
@makasim i know, but your sandbox and master broken now

**Comment by makasim** [comment]
I'll fix it when I have time.

**Comment by muspelheim** [comment]
@makasim I fix it now, np

**Comment by makasim** [comment]
Thanks for the PR.

**Comment by gtrias** [comment]
Could you please make a release with this changes?

Thanks

**Comment by makasim** [comment]
@gtrias 2.1.0 was released yesterday.

https://github.com/Payum/PayumBundle/releases/tag/2.1.0

**Comment by gtrias** [comment]
Thank you! I will try it ASAP
