### ISSUE TITLE
send multiple products to paypal [symfony2]

### ISSUE THREAD

**Issue by aimeric** [Payum/PayumBundle#365]
Hi,

I can send one product and its working fine, but i don't know how to send multiple products to Paypal with the following data(Quantity, description, name).

I'm using payum [1.0.0]
This is what i have done :

 ```
public function validationCommandeAction($id)
    {   $session = $this->getRequest()->getSession();
        $gatewayName = 'express_euro';
        $storage = $this->get('payum')->getStorage('FLY\BookingsBundle\Entity\Commandes');
        $em = $this->getDoctrine()->getManager();
        $commande = $em->getRepository('FLYBookingsBundle:Commandes')->find($id);
        $cart = $session->get('cart');
        $totalTTC = 0;
        dump($commande);
        if (!$commande || $commande->getConfirm() == 1)
            throw $this->createNotFoundException('Your order doesn t exist');
        $commande = $storage->create();
        $commande->setUser($this->get('security.token_storage')->getToken()->getUser());
        $commande->setDate(new \DateTime());
        $commande->setCurrencyCode('EUR');
        $commande->setClientId($this->getUser()->getId());
        $commande->setClientEmail($this->getUser()->getEmail());
        $commande->setNumber(uniqid());
        $commande->setDescription($commande->getDescription() ?: sprintf('Payment %s', $commande->getNumber()));
        $entities = $em->getRepository('FLYBookingsBundle:Post')->findArray(array_keys($session->get('cart')));

        foreach ($entities as $entity) {
            $commande->setTotalAmount($totalTTC = $totalTTC + round($entity->getPrice() * $cart[$entity->getId()]/ $entity->getTva()->getMultiplicate()*100, 2));
        }
        $commande->setConfirm(1);
        $commande->setReference($this->container->get('setNewReference')->reference()); //Service
        $storage->update($commande);

        $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
            $gatewayName,
            $commande,
            'complete' // the route to redirect after capture;
        );


        return $this->redirect($captureToken->getTargetUrl());
    }
```

I'm saving the data about the products like this: 

```
foreach ($entities as $entity) {
            $priceHT = ($entity->getPrice() * $cart[$entity->getId()]);
            $priceTTC = ($entity->getPrice() * $cart[$entity->getId()] / $entity->getTva()->getMultiplicate());
            $totalHT += $priceHT;

            if (!isset($commande['tva']['%' . $entity->getTva()->getValue()]))
                $commande['tva']['%' . $entity->getTva()->getValue()] = round($priceTTC - $priceHT, 2);


            else
                $commande['tva']['%' . $entity->getTva()->getValue()] += round($priceTTC - $priceHT, 2);

            $totalTVA += round($priceTTC - $priceHT, 2);
            $commande['entity'][$entity->getId()] = array(
                'from' => $entity->getAirport(),
                'to' => $entity->getAirport1(),
                'quantity' => $cart[$entity->getId()],
                'priceHT' => round($entity->getPrice(), 2),
                'priceTTC' => round($entity->getPrice() / $entity->getTva()->getMultiplicate(), 2));
        }
```

**Comment by aimeric** [comment]
Please any help will be appreciated!

**Comment by makasim** [comment]
Please provide more info

* do you get any errors, exceptions etc.
* what do you expect to see and what you get in reality?
* what is your version of payum payum bundle and other relevant libs like symfony

**Comment by aimeric** [comment]
Hi Makasim,

I don't have any errors or exceptions. Below is the version of payumBundle that i'm using:
      ```
         "payum/payum-bundle": "1.0",
        "payum/offline": "*@stable",
        "payum/paypal-express-checkout-nvp": "1.2.0",
        "payum/paypal-pro-checkout-nvp": "1.3.0",
        "payum/core": "1.0.*"
     ```

The user can purchase many differents products but each product can be buy once(Quantity 1).

A product contains the following informations: From, To , Arrival DateTime, Departure DateTime, Quantity, PriceHT, PriceTTC, Description.etc....

I'm storing all these informations in the entity commande

`
:{s:3:"%20";d:4.0099999999999997868371792719699442386627197265625;}s:6:"entity";a:1:{i:9;a:5:{s:4:"from";s:12:"Bristol, VA ";s:2:"to";s:16:"Paris ";s:8:"quantity";s:1:"1";s:7:"priceHT";d:20;s:8:"priceTTC";d:24.010000000000001563194018672220408916473388671875;}}s:7: etc.........`

I'm storing all these information because they will help me to create a bill for the customer. But i want also to send these information to paypal so the user can have a summary of the product before to make the payment.

In my ValidationCommandeAction i'm setting the data like this: 

` $commande->setCommande($this->bill());`

I'm expect to have on paypal the summary of the product(s) like this:

Descriptions
from: new york la guardia
To: Paris Orly
DepartureDate: 4-28-2016 20:57
ArrivalDate: 4-29-2016 15:09
Item total: 200 E

from: new york la guardia
To: Bristol, VA
DepartureDate: 4-28-2016 19:50
ArrivalDate: 4-29-2016 15:05
Item total: 158 E

Total: 358 E

For now this is what i get:

![makasim](https://cloud.githubusercontent.com/assets/5352387/14915862/4f0390f2-0e16-11e6-82c5-d4188b0cf69b.jpg)




**This is my ValidationCommande:**

  ```
public function validationCommandeAction($id)
    {
        $session = $this->getRequest()->getSession();
        $gatewayName = 'express_euro';
        $storage = $this->get('payum')->getStorage('FLY\BookingsBundle\Entity\Commandes');
        $em = $this->getDoctrine()->getManager();
        $commande = $em->getRepository('FLYBookingsBundle:Commandes')->find($id);
        $cart = $session->get('cart');
        $totalTTC = 0;
  
        
        dump($commande);

        if (!$commande || $commande->getConfirm() == 1)
            throw $this->createNotFoundException('Your order doesn t exist');

        $commande = $storage->create();
        $commande->setCommande($this->bill());
        $commande->setConfirm(1);
        $commande->setReference($this->container->get('setNewReference')->reference()); //Service
        $commande->setUser($this->get('security.token_storage')->getToken()->getUser());
        $commande->setDate(new \DateTime());
        $commande->setCurrencyCode('EUR');
        $commande->setClientId($this->getUser()->getId());
        $commande->setClientEmail($this->getUser()->getEmail());
        $commande->setNumber(uniqid());
        $commande->setDescription($commande->getDescription() ?: sprintf('Payment %s',    $commande->getNumber()));
        $entities = $em->getRepository('FLYBookingsBundle:Post')->findArray(array_keys($session->get('cart')));

        foreach ($entities as $entity) {
            $commande->setTotalAmount($totalTTC = $totalTTC + round($entity->getPrice() * $cart[$entity->getId()]/ $entity->getTva()->getMultiplicate()*100, 2));
        }
        
        $storage->update($commande);
        $em->flush();

        $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
            $gatewayName,
            $commande,
            'complete' // the route to redirect after capture;
        );


        return $this->redirect($captureToken->getTargetUrl());

        }
  ```


I'm storing the data about the product(s) like this:

  ```
 foreach ($entities as $entity) {
            $priceHT = ($entity->getPrice() * $cart[$entity->getId()]);
            $priceTTC = ($entity->getPrice() * $cart[$entity->getId()] / $entity->getTva()->getMultiplicate());
            $totalHT += $priceHT;

            if (!isset($commande['tva']['%' . $entity->getTva()->getValue()]))
                $commande['tva']['%' . $entity->getTva()->getValue()] = round($priceTTC - $priceHT, 2);


            else
                $commande['tva']['%' . $entity->getTva()->getValue()] += round($priceTTC - $priceHT, 2);

            $totalTVA += round($priceTTC - $priceHT, 2);
            $commande['entity'][$entity->getId()] = array(
                'from' => $entity->getAirport(),
                'to' => $entity->getAirport1(),
                'telephone' => $entity->getTelephone(),
                'pounds' => $entity->getPounds(),
                'id' => $entity->getId(),
                'departuredate' => $entity->getDeparturedate(),
                'arrivaldate' => $entity->getArrivaldate(),
                'address' => $entity->getAddressmeet(),
                'description' => $entity->getDescription(),
                'quantity' => $cart[$entity->getId()],
                'priceHT' => round($entity->getPrice(), 2),
                'priceTTC' => round($entity->getPrice() / $entity->getTva()->getMultiplicate(), 2));
        }
  ```

**Comment by makasim** [comment]
you can set paypal specific fields to details property:

```php
<?php
$commande->setDetails([
    'PAYMENTREQUEST_0_CURRENCYCODE'] => 'USD',
    'PAYMENTREQUEST_0_AMT' => 100,
    'PAYMENTREQUEST_1_CURRENCYCODE'] => 'USD',
    'PAYMENTREQUEST_1_AMT' => 200,
]);
```

**Comment by aimeric** [comment]
Please can you give me one example with my code , so i can undestand.

This is what i have tried but it doesn't work.There is no description in the summary.


 foreach($commande as $entity)
        {
            $commande->setDetails([
            'L_PAYMENTREQUEST_0_DESC0' => $entity->getDescription()]);
        }

**Comment by wawneeds** [comment]
I'm facing the same issue, and have been sweeping the docs, but couldn't find anything conclusive. It would be very much appreciated if you could help out with this.

My situation is as follows:

Client can purchase multiple items at once, I need all the items that the client bought to show on the order summary page of paypal.

I've tried setDetails as you suggested, but I'm not getting anywhere with that, everytime I get an error message I try to fill the missing parameter:

1. Seller ID is mandatory for parallel payments. I added PAYMENTREQUEST_n_SELLERPAYPALACCOUNTID
1. Payment Request ID is mandatory for parallel payments. I added PAYMENTREQUEST_0_PAYMENTREQUESTID

But then I keeping getting that second error.

Here's my code:

`public function payAction(Request $request)
    {
        $gatewayName = 'paypal';

        $storage = $this->get('payum')->getStorage('AppBundle\Entity\Payment');

        $payment = $storage->create();
        $payment->setNumber(uniqid());
        $payment->setCurrencyCode('USD');
        $payment->setTotalAmount(1200); // 1.23 EUR
        $payment->setDescription('Is it an overall description that should
                                   go here ?');
        $payment->setClientId('assil');
        $payment->setClientEmail('client@example.com');
        $payment->setDetails([
            'PAYMENTREQUEST_0_NUMBER0' => 'Item 1 description',
            'PAYMENTREQUEST_0_PAYMENTREQUESTID ' => 'item1ID',
            'PAYMENTINFO_0_PAYMENTREQUESTID ' => 'item1ID',
            'PAYMENTREQUEST_0_AMT' => 600,
            'PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID' => 'assil-facilitator@paypal.com',

            'PAYMENTREQUEST_1_NUMBER0' => 'Item 2 description',
            'PAYMENTREQUEST_1_PAYMENTREQUESTID ' => 'item2ID',
            'PAYMENTINFO_1_PAYMENTREQUESTID ' => 'item2ID',
            'PAYMENTREQUEST_1_SELLERPAYPALACCOUNTID' => 'assil-facilitator@paypal.com',
            'PAYMENTREQUEST_1_AMT' => 600,
        ]);
        VarDumper::dump($payment);

        $storage->update($payment);

        $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
            $gatewayName,
            $payment,
            'done' // the route to redirect after capture
        );

        return $this->redirect($captureToken->getTargetUrl());
    }`

Please help !

**Comment by makasim** [comment]
@wawneeds  You have to set these options: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/PurchaseExamplesController.php#L221

You can find more info about them in Official Paypal docs.

**Comment by wawneeds** [comment]
Thank you very much for your help, this helped me move forward. However I think this should be in the doc somewhere. I'm sure that many of our fellow developers don't necessarily know the internals of the APIs they're willing to use, PayPal for example, and they kind of expect the documentation to put them on track to achieve what they want, example: integrate PayPal payment for their Cart. 

If I wanted to contribute by adding an example, are there any guidelines ?

Thanks again for your help @makasim

**Comment by makasim** [comment]
You can add an article to this folder https://github.com/Payum/Payum/tree/master/src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs

and add a link to it to index.md file

**Comment by 4ssil** [comment]
Shouldn't I put it here https://github.com/Payum/PayumBundle/tree/master/Resources/doc instead ?
The example I have is Symfony based.

**Comment by makasim** [comment]
yes you can put it there as well, If it is related to the bundles, or symfony specific
