### ISSUE TITLE
How to handle user canceled action

### ISSUE THREAD

**Issue by cmanon** [Payum/PayumBundle#366]
I'm trying to use the paypal-express-checkout-nvp (1.2) to make a payment, I've done the setup and process the payment as per the examples I do this when the payment form is submitted:

```
$gatewayName = $form->get('gateway_name')->getData();
$storage = $this->get('payum')->getStorage('Acme\AcmeBundle\Entity\Payment');

$payment = $storage->create();
$payment->setNumber(uniqid());
$payment->setCurrencyCode('MXN');
$payment->setTotalAmount(5000);
$payment->setDescription('Test Payment');
$payment->setClientId($user->getId());
$payment->setClientEmail($user->getEmail());
$payment->setGateway($gatewayName);
$storage->update($payment);
```

The process seems to be working as on the sandbox I get redirected to the paypal, but if the user cancel the payment from the paypal screen it get redirected to the doneAction.

What is the proper way to cancel the payment? As the payment and token records had already been created in the database and if I try to resubmit the form the payment information is already captured.

**Comment by makasim** [comment]
You are redirected to the doneAction. That's expected. the payment status is cancelled. You are expected to find out the payment status in the doneAction and act according to it.

doneAction -does NOT mean the payment was finished successfully. It only means that the purchase process is done.

**Comment by makasim** [comment]
https://github.com/Payum/PayumBundle/blob/master/Resources/doc/purchase_done_action.md

**Comment by cmanon** [comment]
Thanks for the answer, I understand that is the intended behaviour and that such payment has a cancel status, is there a recommended way to resubmit the payment?

**Comment by makasim** [comment]
Create a new one?
