### ISSUE TITLE
Attempted to load trait "GatewayAwareTrait" from namespace "Payum\Core".

### ISSUE THREAD

**Issue by getvivekv** [Payum/PayumBundle#367]
Hi

While configuring it for paypal gateway, I get this error.

```
Attempted to load trait "GatewayAwareTrait" from namespace "Payum\Core".
Did you forget a "use" statement for another namespace?

```
`CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load trait "GatewayAwareTrait" from namespace "Payum\Core". Did you forget a "use" statement for another namespace?" at /home/user/vendor/payum/paypal-express-checkout-nvp/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php line 26 
`

composer.json as per the documentation

`"payum/payum-bundle": "^2.0",
    "payum/paypal-express-checkout-nvp": "^1.3"
`

**Comment by getvivekv** [comment]
Resolved by adding 

`  "php-http/guzzle6-adapter": "^1.1"`

to composer.json

**Comment by makasim** [comment]
What version of `payum/core` or `payum/payum` do you have installed?

**Comment by getvivekv** [comment]
This is from my composer.lock

`{
            "name": "payum/core",
            "version": "1.2.8",
            "target-dir": "Payum/Core",
            "source": {
                "type": "git",
                "url": "https://github.com/Payum/Core.git",
                "reference": "5cb231c5b477a2e7d422cde1b70394a54ef14e40"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Payum/Core/zipball/5cb231c5b477a2e7d422cde1b70394a54ef14e40",
                "reference": "5cb231c5b477a2e7d422cde1b70394a54ef14e40",
                "shasum": ""
            },
            "require": {
                "guzzlehttp/guzzle": "~6.0",
                "league/url": "~3.0",
                "payum/iso4217": "~1.0",
                "php": "^5.5.0|^7.0",
                "twig/twig": "~1.0"
            },
            "require-dev": {
                "doctrine/orm": "2.*",
                "ext-curl": "*",
                "ext-pdo_sqlite": "*",
                "omnipay/dummy": "~2.0",
                "payum/omnipay-bridge": "^1",
                "phpunit/phpunit": "~4.0",
                "propel/propel1": "~1.7",
                "psr/log": "~1.0",
                "symfony/dependency-injection": "~2.8|~3.0",
                "symfony/form": "~2.8|~3.0",
                "symfony/http-foundation": "~2.8|~3.0",
                "symfony/http-kernel": "~2.8|~3.0",
                "symfony/phpunit-bridge": "~2.8|~3.0",
                "symfony/routing": "~2.8|~3.0",
                "symfony/validator": "~2.8|~3.0",
                "zendframework/zend-db": "~2"
            },
            "suggest": {
                "doctrine/mongodb-odm": "~1.1 If you want to store models to mongo doctrin2 ODM",
                "doctrine/orm": "~2.3 If you want to store models to database using doctrin2 ORM",
                "monolog/monolog": "~1.0 If you want to use PSR-3 logger",
                "payum/authorize-net-aim": "self.version If you want to use Authorize.Net AIM payment gateway",
                "payum/be2bill": "self.version If you want to use be2bill payment gateway",
                "payum/omnipay-bridge": "self.version If you want to use omnipay's gateways",
                "payum/payex": "self.version If you want to use payex payment gateway",
                "payum/paypal-express-checkout-nvp": "self.version If you want to use paypal express checkout, digital goods or recurring payments",
                "payum/paypal-ipn": "self.version If you want to use paypal instant payment notifications(Paypal IPN)",
                "payum/paypal-pro-checkout-nvp": "self.version If you want to use paypal pro checkout",
                "payum/paypal-rest": "self.version If you want to use paypal rest gateway",
                "propel/propel": "If you want to store models to Propel2 ORM",
                "propel/propel1": "~1.7 If you want to store models to Propel1 ORM",
                "symfony/dependency-injection": "~2.8|~3.0 If you want to use container aware stuff",
                "symfony/form": "~2.8|~3.0 If you want to use forms",
                "symfony/http-foundation": "~2.8|~3.0 If you want to use HttpRequestVerifier or HttpResponse reply from symfony's bridge",
                "symfony/http-kernel": "~2.8|~3.0 If you want to use HttpRequestVerifier from symfony's bridge",
                "symfony/routing": "~2.8|~3.0 If you want to use TokenFactory from symfony's bridge",
                "zendframework/zend-db": "~2.0 If you want to store models to Zend Db ORM"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.2-dev"
                }
            },
            "autoload": {
                "psr-0": {
                    "Payum\\Core\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Community contributions",
                    "homepage": "https://github.com/Payum/Payum/contributors"
                },
                {
                    "name": "Kotlyar Maksim",
                    "email": "kotlyar.maksim@gmail.com"
                },
                {
                    "name": "Payum project",
                    "homepage": "http://payum.org/"
                }
            ],
            "description": "Payum offers everything you need to work with payments. From simplest use cases to very advanced ones.",
            "homepage": "http://payum.org",
            "keywords": [
                "authorize.net",
                "be2bill",
                "instant payment notification",
                "ipn",
                "jms payment",
                "omnipay",
                "payex",
                "payment",
                "paypal",
                "paypal digital goods",
                "paypal express",
                "paypal pro",
                "paypal rest",
                "recurring payment"
            ],
            "time": "2016-03-24 14:02:42"
        },`

**Comment by makasim** [comment]
I think you need at least 1.3 core
