### ISSUE TITLE
Error SSL

### ISSUE THREAD

**Issue by n1c01a5** [Payum/PayumBundle#370]
I have this error in production : 
```
request.CRITICAL: Uncaught PHP Exception Buzz\Exception\RequestException: "error:14094410:SSL 
routines:SSL3_READ_BYTES:sslv3 alert handshake failure" at /var/www/web/releases
/20160610082653/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php line 29 {"exception":"[object] 
(Buzz\\Exception\\RequestException(code: 35): error:14094410:SSL 
routines:SSL3_READ_BYTES:sslv3 alert handshake failure at /var/www/web/releases
/20160610082653/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:29)"} []
[2016-06-10 17:36:37] security.DEBUG: Write SecurityContext in the session [] []
```

It's working in production in dev mode with app_dev.php but not without (app.php).

Thanks for your help :)

**Comment by n1c01a5** [comment]
For information, if I disable SSL in  
https://github.com/kriswallsmith/Buzz/blob/master/lib/Buzz/Client/AbstractCurl.php#L226&L227 with
```
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
```

It's works.

Is there a better way ?

**Comment by makasim** [comment]
Disabling ssl is not a solution and this is not a problem of Payum. The problem is your local cipher does not supports those paypal require. Try to upgrade kernel. curl, openssl libs.
