### ISSUE TITLE
Request Capture{model: Identity} is not supported

### ISSUE THREAD

**Issue by samanmohamadi** [Payum/PayumBundle#372]
I'am getting this error when redirecting to capture.

    Request Capture{model: Identity} is not supported. Make sure the storage extension for "AppBundle\Entity\Payment" is registered to the gateway. Make sure the storage find method returns an instance by id "290". Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker. 

Do I have to add storage extension explicitly as mentioned [here][1] ?   
According to  [doc][2] it must add the storage extension automatically, Am I right?

 

**My Payum Config :**  

    payum:
        gateways:
            foo:
                factory: foo
                merchant_id: XXX
    
        security:
            token_storage:
                AppBundle\Entity\PaymentSecurityToken: { doctrine: orm }
        storages:
            AppBundle\Entity\Payment: { doctrine: orm }
            AppBundle\Entity\PaymentDetails: { doctrine: orm }

  [1]: https://github.com/Payum/Payum/issues/423#issuecomment-150948591
  [2]: https://github.com/Payum/PayumBundle/blob/master/Resources/doc/storages.md#doctrine-orm

**Comment by makasim** [comment]
Can you try to run `payum:gateway-debug` cli command and see what is there.

**Comment by makasim** [comment]
Why did you added Payment and PaymentDetails, Are you sure you need both?

**Comment by samanmohamadi** [comment]
`]$ php bin/console payum:gateway:debug`
```
zarinpal (Payum\Core\Gateway):
	Actions:
	Payum\Core\Bridge\PlainPhp\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\AuthorizePaymentAction
	Payum\Core\Action\PayoutPayoutAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction
	AppBundle\Payum\Zarinpal\Action\CaptureAction
	AppBundle\Payum\Zarinpal\Action\AuthorizeAction
	AppBundle\Payum\Zarinpal\Action\RefundAction
	AppBundle\Payum\Zarinpal\Action\CancelAction
	AppBundle\Payum\Zarinpal\Action\NotifyAction
	AppBundle\Payum\Zarinpal\Action\StatusAction
	AppBundle\Payum\Zarinpal\Action\ConvertPaymentAction

	Extensions:
	Payum\Core\Extension\EndlessCycleDetectorExtension

	Apis:
	Payum\Core\Bridge\Httplug\HttplugClient
	AppBundle\Payum\Zarinpal\Api

```

**Comment by samanmohamadi** [comment]
`PaymentDetails` was for testing.
 I didn't use it in anywhere in the code.

**Comment by makasim** [comment]
for some reason the storage extension was not registered.

**Comment by makasim** [comment]
You are using the old version, could you try to upgrade to the latest one. I am completely  sure the bug was fixed there.

**Comment by samanmohamadi** [comment]
I'm using the latest version (v 2.1.0).

**Comment by tomaszkowalczyk94** [comment]
I have the same problem.

**Comment by makasim** [comment]
I've run a few tests in the sandbox on the latest version of payum/core payum/payum-bundle. Everything works just fine. So the problem could be related to a custom gateway use. Could you post your `factory: foo` foo factory here?

**Comment by makasim** [comment]
and the way you register it to payum?

**Comment by samanmohamadi** [comment]
```
namespace AppBundle\Payum\Zarinpal;

use AppBundle\Payum\Zarinpal\Action\AuthorizeAction;
use AppBundle\Payum\Zarinpal\Action\CancelAction;
use AppBundle\Payum\Zarinpal\Action\CaptureAction;
use AppBundle\Payum\Zarinpal\Action\ConvertPaymentAction;
use AppBundle\Payum\Zarinpal\Action\NotifyAction;
use AppBundle\Payum\Zarinpal\Action\RefundAction;
use AppBundle\Payum\Zarinpal\Action\StatusAction;
use Payum\Core\Bridge\Spl\ArrayObject;
use Payum\Core\GatewayFactory;

class ZarinpalGatewayFactory extends GatewayFactory
{
    /**
     * {@inheritDoc}
     */
    protected function populateConfig(ArrayObject $config)
    {
        $config->defaults([
            'payum.factory_name' => 'zarinpal',
            'payum.factory_title' => 'zarinpal',
            'payum.action.capture' => new CaptureAction(),
            'payum.action.authorize' => new AuthorizeAction(),
            'payum.action.refund' => new RefundAction(),
            'payum.action.cancel' => new CancelAction(),
            'payum.action.notify' => new NotifyAction(),
            'payum.action.status' => new StatusAction(),
            'payum.action.convert_payment' => new ConvertPaymentAction(),
        ]);


        if (false == $config['payum.api']) {
            $config->defaults($config['payum.default_options']);
            $config['payum.required_options'] = array('merchant_id');

            $config['payum.api'] = function (ArrayObject $config) {
                $config->validateNotEmpty($config['payum.required_options']);

                return new Api((array) $config, $config['payum.http_client'], $config['httplug.message_factory']);
            };
        }
    }
}

```

```
services:
    payum.zarinpal_gateway_factory:
        class: AppBundle\Payum\Zarinpal\ZarinpalGatewayFactory
        tags:
            - { name: payum.gateway_factory, factory: zarinpal }
```

**Comment by makasim** [comment]
you are not using the core factory from the bundle but create your own, hence it knows nothing about storages and so on. So please use a builder:

```yaml
services:
    payum.zarinpal_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [AppBundle\Payum\Zarinpal\ZarinpalGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: zarinpal }
```

**Comment by yurguis** [comment]
I know this is old but just wanted to let you know I had the same problem and found the solution in this last post. Maybe it would be a good idea to add this to the documentation as I couldn't figured it out by reading it.

> you are not using the core factory from the bundle but create your own, hence it knows nothing about storages and so on. So please use a builder:
> 
> ```yaml
> services:
>     payum.zarinpal_gateway_factory:
>         class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
>         arguments: [AppBundle\Payum\Zarinpal\ZarinpalGatewayFactory]
>         tags:
>             - { name: payum.gateway_factory_builder, factory: zarinpal }
> ```

I know this is old but just wanted to let you know I had the same problem and found the solution in this last post. Maybe it would be a good idea to add this to the documentation as I couldn't figured it out by reading it.
