### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by robfrawley** [Payum/PayumBundle#375]
Not sure if this is known or not, but the website that is references throughout the repo (payum.org) is down --- looks like the domain expired on you. Just a friendly heads up.

As a quick aside, I just found this lib/bundle and from a quick first pass at the code base it looks like just what I need --- thanks for all the hard work, I can finally retire my (horrible) Stripe wrapper from a few years back.

**Comment by makasim** [comment]
I had to switch off the site, everything on github now. Now, trying to remove all references to the site. Where did you find them?

**Comment by robfrawley** [comment]
The most obvious place I've seen it is in the GitHub repository descriptions for both this repo and Payum/Payum

**Comment by makasim** [comment]
I removed them

**Comment by Aerendir** [comment]
I'm also found the down domain payum.org.

I think a good idea is to renew the domain for at least one more year and set a redirect to github as it seems the project is dead while it seems to me that is alive!

A redirect will not make the wrong perception. Maybe you'll set a redirect to a page here on github explaining why the web site is shut down... Just a friendly advice from a (wannabe) Payum's user :)

**Comment by makasim** [comment]
It pretty much alive and I am using it on several project and there are a lot of downloads which means others use it too.

There were a redirect for a half of the year already (before it expired).

**Comment by makasim** [comment]
Sorry for inconvenience. It was a bad idea to have a domain from the beginning.

**Comment by Aerendir** [comment]
As you like...
