### ISSUE TITLE
Paypal IPN

### ISSUE THREAD

**Issue by hsb1007** [Payum/PayumBundle#376]
Hi! I am trying to implement Notify action for Paypal IPN.

My service gets called correctly as I am logging the $request object into the database to see what paypal sends through.

However, the $request object is 'Payum\Core\Request\Notify' object and it has my paypal PaymentToken as a model in it, which doesn't tell me anything about the data that Paypal is sending through.

I am not even quite sure which part of code I need to share to get more accurate advice.

If anyone can support, that'd be so much appreciated!

**Comment by makasim** [comment]
The notify request has to be executed several times (there are sub requests). It look like this

Notify with token 
Notify with the model associated with the token. The magic is done in the StorageExtension.


if the implements array access you are done.
If it implements ModelAggregateInterface it is taken and one more sub request is done.

You are writing a extension, are you? If so

Make sure you did something like this 

if ($request instanceof Notify && $request->getModel() instanceof YourClass)

more here: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/instant-payment-notification.md

**Comment by hsb1007** [comment]
Thanks for quick response!

Sorry to keep asking dumb questions..

How do I register the extension that hooks into the action it requires?

And no I didn't have any idea about storage extension. So looks like I am making a progress ;)


And where do I implement array access / model aggregate interface? In extension?

Thank you so much in advance
