### ISSUE TITLE
Doctrine error: The identifier id is missing for a query of

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#378]
Hi Makasim,

I seem to be having a similar issue to #155 but it seems to be only certain customers as for most people it seems to work fine. Did you ever find out what was causing the issue?

PaymentDetails Entity:

```PHP
namespace App\PaymentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\ArrayObject;

/**
 * @ORM\Table(name="payum_payment_details")
 * @ORM\Entity
 */
class PaymentDetails extends ArrayObject
{
    /**
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="\App\OrderBundle\Entity\Orders", inversedBy="payment")
     * @ORM\JoinColumn(name="order_id", referencedColumnName="id")
     */
    private $order;
    
    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $status;
    
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $ts;
```

My prepare in the controller is:
```php
$storage = $this->get("payum")->getStorage("App\PaymentBundle\Entity\PaymentDetails");
$payment = $storage->create();
$payment['CURRENCY']  = $cart->getCurrencyCode();
$payment['AMT'] = $entity->getTotal();
$payment["ACCT"] = new SensitiveValue($form["acct"]);
$payment["CVV2"] = new SensitiveValue($form["cvv2"]);
$payment["EXPDATE"] = new SensitiveValue($form["exp_month"] . $form["exp_year"]);
$payment["BILLTOFIRSTNAME"] = $entity->getNameFirst();
$payment["BILLTOLASTNAME"] = $entity->getNameLast();
$payment->setOrder($orderClass);
$storage->update($payment);
$captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
     $gatewayName, $payment, '_payment_done'
 );
            
return $this->forward('PayumBundle:Capture:do', array('payum_token' => $captureToken));
```

Finally, the stacktrace:
```
/var/www/html/site/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php Line
294
The identifier id is missing for a query of
App\PaymentBundle\Entity\PaymentDetails
#0
/var/www/html/site/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403):
Doctrine\ORM\ORMException::missingIdentifierField('AppBundle\\P...', 'id')
#1
/var/www/html/site/vendor/payum/core/Payum/Core/Bridge/Doctrine/Storage/DoctrineStorage.php(39):
Doctrine\ORM\EntityManager->find('AppBundle\\P...', NULL)
#2
/var/www/html/site/vendor/payum/core/Payum/Core/Storage/AbstractStorage.php(54):
Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage->doFind(NULL)
#3
/var/www/html/site/vendor/payum/core/Payum/Core/Extension/StorageExtension.php(42):
Payum\Core\Storage\AbstractStorage->find(Object(Payum\Core\Model\Identity))
#4
/var/www/html/site/vendor/payum/core/Payum/Core/Extension/ExtensionCollection.php(31):
Payum\Core\Extension\StorageExtension->onPreExecute(Object(Payum\Core\Extension\Context))
#5 /var/www/html/site/vendor/payum/core/Payum/Core/Gateway.php(95):
Payum\Core\Extension\ExtensionCollection->onPreExecute(Object(Payum\Core\Extension\Context))
#6

/var/www/html/site/vendor/payum/core/Payum/Core/Action/ExecuteSameRequestWithModelDetailsAction.php(32):
Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture))
#7 /var/www/html/site/vendor/payum/core/Payum/Core/Gateway.php(107):
Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute(Object(Payum\Core\Request\Capture))
#8
/var/www/html/site/vendor/payum/payum-bundle/Controller/CaptureController.php(35):
Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture))
#9 [internal function]:
Payum\Bundle\PayumBundle\Controller\CaptureController->doAction(Object(Symfony\Component\HttpFoundation\Request))
#10 /var/www/html/site/app/bootstrap.php.cache(3238):
call_user_func_array(Array, Array)
#11 /var/www/html/site/app/bootstrap.php.cache(3197):
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request),
1)
#12 /var/www/html/site/app/bootstrap.php.cache(3351):
Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request),
1, true)
#13 /var/www/html/site/app/bootstrap.php.cache(2536):
Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request),
1, true)
#14 /var/www/html/site/web/app.php(23):
Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#15 {main}
```

**Comment by makasim** [comment]
I think the problem comes from this line:

```
#2
/var/www/html/site/vendor/payum/core/Payum/Core/Storage/AbstractStorage.php(54):
Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage->doFind(NULL)
```

As you can see the id is null, so somehow you created an identity with null id. 

Cannot imagine how this could happen. Sorry

**Comment by liamsorsby** [comment]
Is the creation of the entity not handled by the ```$storage->create()``` method?

It's definately based on the id being null by the time it reaches the ```$storage->update($payment);```

Does the method get called differently depending on the Payment provider?

**Comment by makasim** [comment]
Create method only creates an object, and never store it to db. Where update is responsible for inserting or updating the entity depending wtfeather its new or not. 

https://github.com/Payum/Payum/blob/master/src/Payum/Core/Storage/AbstractStorage.php#L26

**Comment by makasim** [comment]
Make sure you call update method before using it with createXXXToken

**Comment by liamsorsby** [comment]
As you can see from the below. the update method is called directly before the method.
```php
$storage->update($payment);
$captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
     $gatewayName, $payment, '_payment_done'
 );
```
It does however look as if the update method never run or it doesn't return the entity. 

Any thoughts on how to possibly debug this?

**Comment by liamsorsby** [comment]
Just checked the structure of the database table and can confirm that auto_increment is definately assigned to the table.

I am also use 1.0.0, obviously there will be bug fixes in the more recent versions. Have there been any bug fixes on the update method at all?

**Comment by makasim** [comment]
I believe there is not any such fixes. The doctrine storage works quite well for me since early versions.

**Comment by liamsorsby** [comment]
I will keep an eye out and see if I can possibly debug it. If I find anything I will let you know or even create a PR.

**Comment by makasim** [comment]
Looking forward to it.

**Comment by liamsorsby** [comment]
One thing I have noticed is that when I run the console command app/console paypal_express --model-class=App\PaymentBundle\Entity\PaymentDetails --model-id=1 it states that a storage for the model doesn't exist. Then if I run app/console payum:gateway:debug it shows the extension paypal_express and with the model class above.

The error I get for this is A storage for model AppPaymentBundleEntityPaymentDetails are not registered. There are storages for next models: App\PaymentBundle\Entity\PaymentDetails, the if I double up the back slashes it then just returns failed. I know this may not be related but it's worth a shot

**Comment by liamsorsby** [comment]
@makasim quick update which makes the issue even more bizarre. When the  environment is changed to app_dev.php the payment works fine. When the environment is switched back to app.php then the error is thrown.

**Comment by liamsorsby** [comment]
@makasim I've upgrade to PayumBundle 2.1.0 and it seems to have fixed this issue.

**Comment by makasim** [comment]
@liamsorsby glad to hear that though I dont know how
