### ISSUE TITLE
Any documentation for Laravel?

### ISSUE THREAD

**Issue by robbens** [Payum/PayumBundle#379]
Is there any documentation for Klarna Invoice when using Laravel 5.3?

**Comment by makasim** [comment]
There is not dedicated docs on this topic for Laravel. But It is easy to adopt a tutorial for plain php 
https://github.com/Payum/Payum/blob/master/src/Payum/Klarna/Invoice/Resources/docs/get-it-started.md

to be used with laravel.

Laravel docs: https://github.com/Payum/PayumLaravelPackage/blob/master/docs/index.md
