### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by sblmasta** [Payum/PayumBundle#380]
**Console input:**

`> composer require "payum/payum-bundle" "payum/paypal-express-checkout-nvp"`

**Console output:**

Using version ^2.1 for payum/payum-bundle
Using version ^1.3 for payum/paypal-express-checkout-nvp
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - payum/core 1.3.6 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.3.5 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.3.3 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/payum-bundle 2.1.0 requires payum/core ^1.3.3 -> satisfiable by payum/core[1.3.3, 1.3.5, 1.3.6].
    - Installation request for payum/payum-bundle ^2.1 -> satisfiable by payum/payum-bundle[2.1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by makasim** [comment]
according to the doc you have to do it like this

```
php composer.phar require payum/paypal-express-checkout-nvp php-http/guzzle6-adapter
```

https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs/get-it-started.md

You can choose another http client instead of guzzle if you need.

**Comment by makasim** [comment]
And this line of output 

```
payum/core 1.3.6 requires php-http/client-implementation ^1.0 -> no matching package found.
```

is just telling you  about it.
