### ISSUE TITLE
Documentation: Remove the link to the Sandbox as it doesn't exist

### ISSUE THREAD

**Issue by Aerendir** [Payum/PayumBundle#383]
The link to the Sandbox in the main `README.md` file is broken. I think there isn't yet a public sandbox, but only an app that anyone can download locally to test the bundle: https://github.com/makasim/PayumBundleSandbox

I think the link should be fixed, or not? Anyway I'm going to prepare a pull request.

**Comment by makasim** [comment]
the fix was merged
