### ISSUE TITLE
Doc: Stripe checkout example extends wrong class

### ISSUE THREAD

**Issue by Aerendir** [Payum/PayumBundle#388]
In the Stripe Checkout doc the example class extends `\ArrayObject` while in the rest of the documentation of the Payum Library are used some methods from the `Payum\Core\Model\Payment`.

Fix the example to extend from this class instead of `\ArrayObject`.

Pro: Rename the class as `Payment` from `PaymentDetaills` to be consistent with the rest of the documentation.

**Comment by makasim** [comment]
FYI: Pyum works with ArrayObject (all gateways support it) and some of them support Payment model.

**Comment by makasim** [comment]
@Aerendir 

ArrayObject - (or simply array) has a gateway specific format, it gives ability to customize stuff but does not provide any unifications. This is something I developed first
Payment - provides a unification. if the gateway supports payment model you can use it with it. but not all gateway could be covered by Payment model interface.

**Comment by Aerendir** [comment]
Ok, so, speaking of Stripe, is more correct to extend from `BasePayment` as it is supported by the gateway, right?

**Comment by makasim** [comment]
You can do that, 
Also you can create your own model (Payment or Order) and use it with Payum. You have to make sure there is a conver action from your model format to gateway specific format (array). 

for example https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/Action/ConvertPaymentAction.php#L18

**Comment by Aerendir** [comment]
Ok, I understand. Now I'm going to fix this on the Sandbox as I've seen the subscription example doesn't work. I'll try to first make it work on the sandbox and then I'll implement it in my app.
