### ISSUE TITLE
Why there are both Payment and PaymentDetails?

### ISSUE THREAD

**Issue by Aerendir** [Payum/PayumBundle#390]
Copied from [PayumBundleSandbox](https://github.com/makasim/PayumBundleSandbox/issues/79#issuecomment-247555042).

I'm looking into the bundle and seen that there are two different entities: Acme\PaymentBundle\Entity\PaymentDetails and Acme\PaymentBundle\Entity\Payment.

Is there a reason for this or is only something to fix?

I think this is linked to the issue #388.

Can you give me some advice about this so I can fix and make them omogeneous? It is now very confusing!

**Comment by makasim** [comment]
I meant here https://github.com/Payum/PayumBundle/issues/388
