### ISSUE TITLE
What about a 2.1.1 version?

### ISSUE THREAD

**Issue by Aerendir** [Payum/PayumBundle#391]
Ok, I've now again a fresh copy of the sandbox and run `composer install`.

As told in [PayumBundleSandbox issue #73](https://github.com/makasim/PayumBundleSandbox/issues/73), the non-development version of the PayumBundle is used.

This causes an error when installing the sandbox as [this commit](https://github.com/makasim/PayumBundleSandbox/commit/978fe0d3fd83f97e8701af19f3b3babdff0c6fb3) imports all routes at once, but in the current stable version of the PayumBundle this file is not yet present.

Creating a patch version `2.0.1` will make the stable PayumBundleSandbox to download the new version and work out of the box without changing nothing.

**Comment by makasim** [comment]
I'll do the release soon.

**Comment by makasim** [comment]
and update sandbox deps.

**Comment by Aerendir** [comment]
Ok! In the mean time I'll use `@dev`...

**Comment by makasim** [comment]
done

**Comment by Aerendir** [comment]
Great! :)
