### ISSUE TITLE
Recurring Payment : How to catch the second payment ?

### ISSUE THREAD

**Issue by flierville** [Payum/PayumBundle#392]
Hello, i'am interesting by using the Reccuring Payment for my Web site ([Like your example](https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php))

My Need:
 - A customer buys an advert space in my website
 - The advert space is sell for example 100$ for 1 year
 - When I recieve the first payment I update the End Date to "Now + 1 Year"
 - For the next automatic payment (in an year) I update the End Date to "Now + 1 Year"

But I dont understand something : in a year how can I know that automatic recurring payment has occurred ? Paypal send me a web request ?

Thank you

**Comment by makasim** [comment]
Paypal does the whole job related to subscriptions, you have to correctly tell it about the period amount and so. Paypal cares about the rest. If it cannot do something or the subscription is cancelled for example it sends a notification back to you.

**Comment by makasim** [comment]
Payum does not provide any additions or abstractions over that functionality. So you can read the Paypal's docs.
