### ISSUE TITLE
cURL error when "live credentials" paypal

### ISSUE THREAD

**Issue by SMartignier** [Payum/PayumBundle#393]
Hello,

First of all thank you for this bundle.

I use your bundle for paypal payment (express_checkout).

I'm not using the latest version of your bundle because the project i'm working on is on Symfony 2.7.
So here it's my composer.json :
`"payum/payum-bundle": "1.0.3",
   "payum/payum": "1.1.4",
   "payum/core": "1.3.0",
   "php-http/guzzle6-adapter": "^1.0"`

My config :
`payum:
    security:
        token_storage:
            AppBundle\Entity\Announce\PaymentToken: { doctrine: orm }
    storages:
            AppBundle\Entity\Announce\PaymentAnnounce: { doctrine: orm }
    gateways:
            paypal_express_checkout:
                paypal_express_checkout_nvp:
                    username:   "%paypal_username%"
                    password:   "%paypal_password%"
                    signature:  "%paypal_signature%"
                    sandbox:    "%payment_test%"`

When i'm testing with sandbox parameters (with my personal account it's working).
My problem is that when i want to go "live" it doesn't work anymore.
I have access to a business account on paypal so i have credentials (username, password, signature) for the api and i turn sandbox to false (it's the right think to do no?). But then i've got an "cURL error 51: SSL: certificate verification failed (result: 5)" on payment/capture.
`(// Create a connection exception if it was a specific error code.
        $error = isset($connectionErrors[$easy->errno])
            ? new ConnectException($message, $easy->request, null, $ctx)
            : new RequestException($message, $easy->request, $easy->response, null, $ctx);
        return new RejectedPromise($error);
    })`

I have search for a long time and i don't find any working solutions.
I have to admit i'm not sure if it's a problem with your bundle or with anything of my environnement (Mac El Capitan, PHP 5.6.23 by Liip, curl 7.47.1)

Thanks in advance for your help.

**Comment by makasim** [comment]
The error does not relates to Payum. Long story short you do not have required chiper on the prod server. 

More here https://github.com/Payum/PayumBundle/issues/381, https://github.com/Payum/PayumBundle/issues/370

**Comment by makasim** [comment]
Are you trying sandbox and prod credentials on the same computer? The sandbox works where prod does not?

**Comment by makasim** [comment]
>  the api and i turn sandbox to false (it's the right think to do no?)

sure

**Comment by SMartignier** [comment]
Hi,

Thanks for the amazing reaction Oo

Yes i'm testing on the same computer (i'm making a traineeship so i don't have access to the prod server).
I will take a look at issues 381 and 370.

**Comment by makasim** [comment]
I dont think it is related to the problems I linked to.

**Comment by SMartignier** [comment]
Updated last comment

**Comment by SMartignier** [comment]
Concerning "The error does not relates to Payum. Long story short you do not have required cipher on the prod server.", how can i have the required cipher?

**Comment by makasim** [comment]
Now I am not sure you have that problem since it works in sandbox mode.  But if you still want to try make sure you have the latest versions of php, curl, openssl on your computer.

**Comment by SMartignier** [comment]
My code is working in prod, so it's probably an error of my environnement.

Have you an exemple (can't find in the doc downloaded with my version of the bundle) of making recurring payment with paypal?

Thanks

**Comment by makasim** [comment]
you can use the doc from payum lib (it is plain php examples) and examples from the sandbox https://github.com/makasim/PayumBundleSandbox

find correct version of the sandbox with required version like you have
