### ISSUE TITLE
Dynamic Gateways not loading all entities

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#399]
Hi Makasim,

I'm currently integrating our platform to use PayumBundle on our admin without sanata Admin. Everything is configured and works correctly. The only issue I am facing is with the dynamic registry (https://github.com/Payum/Payum/blob/master/src/Payum/Core/Registry/DynamicRegistry.php).

How would I go about injecting the available gateways into Payum from the database or should this be done automatically? When paypal express calls:

```php
$captureToken = $this->get("payum")->getTokenFactory()->createCaptureToken(
    "paypal_express_gateway_name",
    $payment,
    "done"
);
return $this->redirect($captureToken->getTargetUrl());
```

The database values are created in the payment details table and the token but I get the following error from one of the Payum files:

> Gateway "paypal_express_gateway_name" does not exist.

The error comes from:
in vendor/payum/core/Payum/Core/Registry/AbstractRegistry.php at line 93

```php
        {
            if (!isset($this->gateways[$name])) {
                throw new InvalidArgumentException(sprintf('Gateway "%s" does not exist.', $name));
            }
            return $this->getService($this->gateways[$name]);

```
I've checked the database which states the names are the exact same. I've also gone into the vendor file and done a quick var_dump($this->gateways) which returns two empty arrays which is the same number of gateways I have available.

Can you confirm that simply creating an Entity called GatewayConfig which implements Payum\Core\Model\GatewayConfig\BaseGatewayConfig should automatically pull in the configs?

Thank you,
Liam

**Comment by liamsorsby** [comment]
I've also tried the following command: 

> app/console payum:gateway:debug

 which throws the following error: 
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to Payum\Core\GatewayFactory::create() must be of the type array, null given, called in /var/www/h
  tml/site/vendor/payum/core/Payum/Core/Registry/DynamicRegistry.php on line 170 and defined
```

**Comment by makasim** [comment]
have you configured it correctly in config.yml? 

```
#app/config/config.yml

payum:
    dynamic_gateways:
        sonata_admin: true
        config_storage: 
            Acme\PaymentBundle\Entity\GatewayConfig: { doctrine: orm }
```
If you configure that section it must add a config storage to payum builder and the payum builder will use it to create a chained gateways registry, one of those registries will be a dynamic one. which do the job. The whole concept is lazy as possible, so anything loaded to php if not needed

https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/configure-gateway-in-backend.md

**Comment by liamsorsby** [comment]
@makasim All of my config is the same other than I haven't set the sonata_admin: true as I am not using sanata admin. Would this make a difference at all?

**Comment by makasim** [comment]
Nope, it should not make any difference

**Comment by liamsorsby** [comment]
@makasim In which case yes. The config is exactly the same. The error appears to be originating from 
```php
$gateway = $this->getPayum()->getGateway($token->getGatewayName());
```
From the payum/payum-bundle/Controller/CaptureController.php at line 34

When you created the sanata bundle plugin and the Dynamic gateway. Did you have to create any additional DI to inject the database values into the registry gateway?

**Comment by makasim** [comment]
Nope, you should not do any additional stuff. I'll try to find time and take a look. Ping me next week if I do not reply

**Comment by liamsorsby** [comment]
No Problem. I will continue to look into this. I have already gotten a start on this as the Abstract model seems to not work unless the gateway_name is in the config. Which has gotten past that error. The error I seem to be coming across now is that config returns null when using DoctrineStorage findBy(array("gatewayName" => $name)) and returns an error on the function createGateway as the method in the return statement requires an array. Which the database has but the model seems to return it as null. I will continue to look into this further and let you know If I fix it.

**Comment by liamsorsby** [comment]
@makasim All sorted. It was completely down to extending the GatewayConfig and having the factory name which also needs to be in the config. The second error I explained above was my fault as I manually put the factory name in incorrectly which caused an error on the array rendering it null. Thank you for your time and I apologise for waisting it as I have fixed this by myself.

**Comment by makasim** [comment]
@liamsorsby no problem. Do you think there is something we can improve in payum itself, like add an exception with clear message?

**Comment by liamsorsby** [comment]
@makasim No the exception message was clear enough (although it did take me about 2 hours to figure it out). I'm not sure if the docs are being updated soon but it maybe useful to mention that the gateway_name needs to be in the config as well. Other than that I think most of the exceptions are very clear.

**Comment by Arjyouu97** [comment]
> @makasim All sorted. It was completely down to extending the GatewayConfig and having the factory name which also needs to be in the config. The second error I explained above was my fault as I manually put the factory name in incorrectly which caused an error on the array rendering it null. Thank you for your time and I apologise for waisting it as I have fixed this by myself.

having the same issue , do u still remember how did you solved this issue
