### ISSUE TITLE
Offline factory status codes

### ISSUE THREAD

**Issue by liamsorsby** [Payum/PayumBundle#400]
How do you make the offline factory give a completed status? Is it possible to do this or is only pending the only status code that can be used?

My thoughts are if I use the offline factory for something like payment on delivery then the payment status should be set to completed as the payment will be recieved upon delivery of the goods.

Regards,
Liam

**Comment by makasim** [comment]
Set field `paid` true in payment details and it will be marked as completed. 

https://github.com/Payum/Payum/blob/master/src/Payum/Offline/Action/CaptureAction.php#L22

**Comment by liamsorsby** [comment]
Thank you.
