### ISSUE TITLE
Token missing exception

### ISSUE THREAD

**Issue by demianchuk** [Payum/PayumBundle#402]
Hi!

I have a problem with token exception.
Situation is next
1. I am create payment, tokens are created in database.
2. The redirection to payment gateway is done
3. I am doing the payment via credit card using payU gateway
4. Transaction is done

And here two possible variants are possible:
1. I am redirecting automatically in 2 sec on done action and everything works fine
2. I am clicking button "Back to shop", that is visible only two seconds and get Exception: "Token is not found". Token is really deleted from db though previously it was present there. But I cant understand which process is doing that and why. AfterCaptureRoute - no, because I am still not redirected to that page. I have only one line in my code that delete toke - that is done action and that all. 

Can some another process in payum bundle do it?
Generally transaction is done and I see that payment status has changed on "success".
![exc](https://cloud.githubusercontent.com/assets/19871155/20388452/2e80df30-acc5-11e6-93b1-60b62e22d38f.jpg)

**Comment by makasim** [comment]
I suppose a notification request comes to your site before a user come back and it uses capture token (for some reason). If it so, notification should use separate url (createNotifyToken)

**Comment by makasim** [comment]
Could you please check this first easy case, before we go too deep.

**Comment by makasim** [comment]
> Can some another process in payum bundle do it?

no. track coming requests most likely it is notification from PayU

**Comment by demianchuk** [comment]
While creating payment I have next after_url in token table in db:
1. http://clicktrans.com.dev/app_dev.php/payment/notify/42Ih0pZVUVESzoFcEG-qYKgl7kfapJ87p8-lh5RJF_A
2. http://clicktrans.com.dev/app_dev.php/payment/capture/H-_mk-gk56ydSomY2LxXThaNf9PPMkiSSsqEcRvW8ZY
3. http://clicktrans.com.dev/app_dev.php/payments-payment-done?payum_token=RDR3REz23L6Z0AB-AZtVFFoYgdJL5dYPNR746Glu3w4
![tokens1](https://cloud.githubusercontent.com/assets/19871155/20388736/8df92a7a-acc6-11e6-9ca3-fd075f74ca08.jpg)

**Comment by demianchuk** [comment]
After getting exception: notify_url with token is only  present
![tok2](https://cloud.githubusercontent.com/assets/19871155/20388855/0ddc6f9a-acc7-11e6-96c1-2d6ba4126e8a.jpg)

**Comment by demianchuk** [comment]
Like notification hash wasn't used at all

**Comment by demianchuk** [comment]
But done action was already running

**Comment by demianchuk** [comment]
Cant understand how is it possible

**Comment by demianchuk** [comment]
So, I suppose it is not notify problem

**Comment by demianchuk** [comment]
Ok, I in logs I see that notify is coming
{"orders":[{"orderId":"KX82HMMMNL161117GUEST000P01","extOrderId":"20037","orderCreateDate":"2016-11-17T13:51:30.865+01:00","notifyUrl":"http:\/\/clicktrans.com.dev\/payment\/notify\/X_0gB0njhZXRqlTN55CRgos9mbRVAeqSSa2pf9ynMMc","customerIp":"78.31.154.107","merchantPosId":"220535","description":"Top up your account. User: test007(381510), Operation ID: 20037","currencyCode":"EUR","totalAmount":"100","buyer":{"customerId":"guest","email":"test2120071@clicktrans.pl","firstName":"test","lastName":"regggttt","language":"en"},"payMethod":{"type":"CARD_TOKEN"},"status":"COMPLETED","products":[{"name":"Top up your account. User: test007(381510), Operation ID: 20037","unitPrice":"100","quantity":"1"}]}],"status":{"statusCode":"SUCCESS","statusDesc":"Request processing successful"},"properties":[{"name":"PAYMENT_ID","value":"788363738"}]}

**Comment by demianchuk** [comment]
but after all notify token is not deleted while capture and done tokens are deleted

**Comment by demianchuk** [comment]
Any ideas how is possible?

**Comment by makasim** [comment]
could you post your prepare and done actions please?

**Comment by demianchuk** [comment]
public function prepareVerificationAction(Request $request)
    {
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw new \Exception('You must be logged in');
        }

        $paymentManager = $this->get('app.payment.payment_manager');
        $captureToken = $paymentManager->createVerificationPayment($this->getUser());

        return $this->redirect($captureToken->getTargetUrl());
    }

**Comment by demianchuk** [comment]
public function createVerificationPayment(User $user)
    {
        $provider = self::VERIFICATION_PROVIDER;
        $afterCaptureRoute = self::DEFAULT_AFTER_CAPTURE_ROUTE; //payments_payment_done

        $company = $user->getCompany()->getAddress()->getCountry() ? $user->getCompany() : $this->companyManager->fillFromNotVerifiedData($user->getCompany());
        $countryCode = $company->getAddress()->getCountry();

        $storage = $this->payum->getStorage(PaymentTransaction::class);

        $currency = $user->getSettings()->getCurrency();
        $amount = Payment::DEFAULT_VERIFICATION_AMOUNT;

        //get payment gateway parameters from config
        $gatewayParameters = $this->gatewayMapper->getGatewayParameters($user, $provider);

           //create payment at first
        $payment = new Payment();
        $payment->setStatus(Payment::STATUS_WAITING);
        $payment->setUser($user);
        $payment->setUserSaldoAccount($user->getActiveSaldoAccount());
        $payment->setType(Payment::TYPE_VERIFICATION);
        $payment->setAmount($amount);
        $payment->setCurrency($currency);

        $paymentForm = PaymentTransaction::PAYMENT_FORM_CARD;

        //create payment transaction
        $paymentTransaction = $storage->create();
        $paymentTransaction->setPaymentForm($paymentForm);
        $paymentTransaction->setCurrencyCode($currency);
        //payment transaction has to be in integer(groszy)
        $paymentTransaction->setTotalAmount(round($amount * 100));
        $paymentTransaction->setProvider($gatewayParameters['name']);
        $paymentTransaction->setPos($gatewayParameters['id']);
        $paymentTransaction->setLocale($this->gatewayMapper->getGatewayLocale());
        $paymentTransaction->setClientId($user->getId());
        $paymentTransaction->setClientEmail($user->getEmail());

        $descriptionTranslations = $this->translationHelper->getPaymentTranslations();

        $paymentTransaction->setDescription($descriptionTranslations[Payment::TYPE_VERIFICATION]);

        $details = array(
            'firstName' => $user->getFirstName(),
            'lastName' => $user->getLastName()
        );
        $paymentTransaction->setDetails($details);
        $paymentTransaction->setPayment($payment);

        $storage->update($paymentTransaction);

        $captureToken = $this->payum->getTokenFactory()->createCaptureToken(
            $gatewayParameters['name'],
            $paymentTransaction,
            $afterCaptureRoute // the route to redirect after capture
        );

        return $captureToken;

    }

**Comment by demianchuk** [comment]
/**
     * @Route("/payments-payment-done", name="payments_payment_done")
     * @param Request $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function donePaymentAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $paymentManager = $this->get('app.payment.payment_manager');
        $paymentOperations = $this->get('app.payment.payment_operations');

        $status = $paymentManager->realizePayment($request);
        $paymentTransaction = $status->getFirstModel();
        $user = $paymentTransaction->getPayment()->getUser();
        $verificationManager = $this->get('app.verification_manager')->load($user);
        $paymentBlockType = !is_null($verificationManager->getBlock(CardPaymentBlock::BLOCK_KEY)) ? CardPaymentBlock::BLOCK_KEY
            : PaymentBlock::BLOCK_KEY;

        if (!$paymentTransaction) {
            throw new \Exception('Payment transaction doesn\'t exists');
        }

        $payment = $paymentTransaction->getPayment();

        if ($status->isCaptured() && $paymentTransaction->getStatus() != PaymentTransaction::STATUS_COMPLETED) {
            // payment succeeded
            $paymentTransaction->setStatus(PaymentTransaction::STATUS_COMPLETED);

            if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
                if ($paymentBlockType == PaymentBlock::BLOCK_KEY) {
                    //for polish couriers - bank transfer
                    $verificationManager->resetBlock($paymentBlockType);
                    $verificationManager->finishStep($paymentBlockType, PaymentBlock::STEP_MAKE_PAYMENT);
                } else {
                    //for foreign couriers - card
                    $verificationManager->resetBlock($paymentBlockType);
                    $verificationManager->finishBlock($paymentBlockType);
                }
            }

            $saldoOperation = $paymentOperations->prepareSaldoOperationForPayment($paymentTransaction, SaldoOperation::TYPE_SALDO_UP);
            $em->persist($saldoOperation);

        } elseif ($status->isPending()) {
            //when status is still pending then set step as pending as well
            if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
                if ($paymentBlockType == PaymentBlock::BLOCK_KEY) {
                    $verificationManager->startStep($paymentBlockType, PaymentBlock::STEP_MAKE_PAYMENT);
                } elseif ($paymentBlockType == CardPaymentBlock::BLOCK_KEY) {
                    $verificationManager->startStep($paymentBlockType, CardPaymentBlock::STEP_MAKE_PAYMENT);
                }
            }

            $paymentTransaction->setStatus(PaymentTransaction::STATUS_WAITING);
            $payment->setStatus(Payment::STATUS_WAITING);
        } elseif ($status->isCanceled()) {
            if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
                $this->rejectVerificationPayment($paymentBlockType);
            }

            $paymentTransaction->setStatus(PaymentTransaction::STATUS_CANCELLED);
            $payment->setStatus(Payment::STATUS_CANCELLED);
        } elseif (!$status->isCaptured()) {
            if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
                $this->rejectVerificationPayment($paymentBlockType);
            }

            $paymentTransaction->setStatus(PaymentTransaction::STATUS_REJECTED);
            $payment->setStatus(Payment::STATUS_REJECTED);
        }

        if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
            //For verification - always set default amount - in case if some convertations were done
            $paymentTransaction->setTotalAmount(Payment::DEFAULT_VERIFICATION_AMOUNT * 100);
            $payment->setAmount(Payment::DEFAULT_VERIFICATION_AMOUNT);
        }

        $em->persist($paymentTransaction);
        $em->persist($payment);

        $em->flush();

        $redirectRoute = 'my_account_payments';

        if ($paymentTransaction->getPayment()->getType() == Payment::TYPE_VERIFICATION) {
            $redirectRoute = 'verification_dashboard';
        }

        return $this->redirectToRoute($redirectRoute);
    }

**Comment by demianchuk** [comment]
public function realizePayment(Request $request)
    {
        $token = $this->payum->getHttpRequestVerifier()->verify($request);
        $gateway = $this->payum->getGateway($token->getGatewayName());

        //invalidate the token. The url could not be requested any more.
        $this->payum->getHttpRequestVerifier()->invalidate($token);

        $gateway->execute($status = new GetHumanStatus($token));

        return $status;
    }

**Comment by demianchuk** [comment]
Dont know if it will be easy to understand it

**Comment by demianchuk** [comment]
I found that payu is sending me the same notification with success status twice. I suppose that creates problem. I dont know whole payum mechanism but I also notices that token is not deleted only when I comment that line in CaptureController.php : $this->getPayum()->getHttpRequestVerifier()->invalidate($token),  AND  that line in my done action: $this->payum->getHttpRequestVerifier()->invalidate($token);

If at least one line is uncommented - done and capture tokens are deleted. 
Does notify action with success status also can run done or capture action? if yes - than it explains my problem

I also want to ask if is it possible not to delete token in payum actions(run it in some unsafe mode) but process token removing on my own way - for example in some listener when status of payment is changed on success ?

P.S. Sorry that disturb you, but it really not quite typical situation. I and 2 other developers spent on it half a day - but we still cant find solution. In any case thank you for your previous answers.

**Comment by makasim** [comment]
> I also want to ask if is it possible not to delete token

The done action is your own. You can put or remove any logic from there.

**Comment by demianchuk** [comment]
Yes, but not capture action

**Comment by solverat** [comment]
@makasim @demianchuk: We experience the same issue within a current development. After the payment was successfully captured on offsite, the gateway creates a confirm page. This page redirects the customer within a `window.setTimeout()` function to the `/payment/capture/xy` page after 5 seconds. They also provide a simple button with a `onclick="redirect(/payment/capture/xy)"` which also leads to the same page.  

If the user hits that button, the request gets triggered twice. The first one will invalidate after the payment has been successfully processed. The second one however fires the `A token with hash "xy" could not be found.`.

I will leave this note for others whom may have the same annoying issue. This is most probably not a payum thing but we also still searching for the "right" solution.
