### ISSUE TITLE
Refund problem

### ISSUE THREAD

**Issue by iometrine** [Payum/PayumBundle#405]
Hi,

I follow the documentation to install payum on my symfony project.
I work to begin with the gateway 'offline', like it's explained.

The payment seem to work, but when i use the refund module, I got the follow error:

Request Refund{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

Please see my code:

`        $gateway = $this->get('payum')->getGateway('offline');

       // i get the payment that i need refund
        $payment = $booklink->getPayment();

        $gateway->execute(new Refund($payment));

        $gateway->execute($status = new GetHumanStatus($payment));
`

Can you help me please ?

**Comment by makasim** [comment]
that's simple. it does not support it https://github.com/Payum/Payum/tree/master/src/Payum/Offline/Action

**Comment by iometrine** [comment]
So, Is  there a gateway to make a refund ?

**Comment by makasim** [comment]
It is not implemented. You can add a refund action

**Comment by iometrine** [comment]
Yes i got that.
But which other gateway implement refund ?

**Comment by makasim** [comment]
> But which other gateway implement refund ?

there are some, klarna invoice, paypal pro, sofort. https://github.com/Payum/Payum/search?utf8=%E2%9C%93&q=RefundAction

> And Where can i find a documentation to add a refund function ?

there is no such. That's easy just add an action that can take data from your model and send corret request to payment gateway, than properly set response data back to the model. status action has to be adjusted too.

**Comment by makasim** [comment]
> Do i need to use this ?

Paypal Express checkout does not use paypa official sdk. There is a Api class you have to add a refund api call there and than add an action that calls it.

**Comment by iometrine** [comment]
Thank you for your response, but i'm new in symfony and i don't understant what exactely i need to do.
I don't know as well the logic of refund (doest it add a new line in payment with negative value etc...)

If it's quick, can you add this fonctionnality on the gateway  paypal-express-checkout-nvp ?

Like that, i 'll be able to do on offline gateway, and maybe commit it on this bundle.

**Comment by makasim** [comment]
Sorry I cannot do it for free

**Comment by iometrine** [comment]
Oh, but i don't understand why this functionnality is not implemented, the logic of open source is free, isn't it ? 
Is it  too long to develop it ?

Can you explain the process so that I can do it ?

**Comment by makasim** [comment]
That's easy. I implemented what I needed, and I merged what others needed and developed. Ofcource there features that are not implemented but there is a possibility to add them. 
As for me It is not hard to do that but I have a lot of other stuff to play with in my free time. 

> Can you explain the process so that I can do it ?

 I've already explained that above.

**Comment by iometrine** [comment]
Thank you makasim, i'll try to implement it
