### ISSUE TITLE
[DOC] - Path documentation

### ISSUE THREAD

**Issue by nietzcheson** [Payum/PayumBundle#406]
The [link](Payum/PayumBundle: Payum offers everything you need to work with payments. From simplest use cases to very advanced ones.) to the bundle documentation points to payum / payum and not to payum / payum-bundle

**Comment by makasim** [comment]
That's how it is done, whole documentation for payum itself and its extensions are stored in payum/payum repo. 

If you know how to improve it tell me or even better send a PR

**Comment by nietzcheson** [comment]
You are right. Only if I get directly to the bundle and want information from this, going to Payum would create confusion. I'd rather have two links. One for the bundle's own documentation; valuable information. And another link to support me from the bookstore... Add PR: #407
