### ISSUE TITLE
Trying to use doctrine in PayumExtension.php

### ISSUE THREAD

**Issue by carlinhus** [Payum/PayumBundle#408]
I'm trying to configure the bundle with parameters that are saved into database instead YAML. Could you tell me how to inject doctrine in that container?

Regards.

**Comment by makasim** [comment]
Not sure I have the question right. That's possible to gateway configs to database. Here's some docs: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/configure-gateway-in-backend.md and symfony specific https://github.com/Payum/PayumBundle/blob/master/Resources/doc/configure-payment-in-backend.md

**Comment by carlinhus** [comment]
I will look at your links, thanks. I was trying to configure the Gateway into CompilerPass with the ContainerBuilder class, but Doctrine is used in there by PayumBundle, so I can't access to Doctrine. :)
