### ISSUE TITLE
PayumBundle breaks autowiring of Doctrine EntityManagerInterface

### ISSUE THREAD

**Issue by tehplague** [Payum/PayumBundle#412]
The Payum Symfony bundle currently registers the following service to use the Doctrine ORM:
```
        <service 
            id="payum.entity_manager" 
            class="Doctrine\ORM\EntityManager"
            public="false"
        >
            <factory service="doctrine" method="getManager" />
        </service>
```

This breaks any service that wants to autowire the EntityManager since it actually registers a second identical service that provides access to the very same class instance of the ORM.

It should be rewritten to
```
        <service id="payum.entity_manager" alias="doctrine.orm.default_entity_manager" public="false" />
```
That way, the DI container knows that this really is just an alias and the ambiguity between Payum's alias and the core ORM service will be resolved. `doctrine.orm.default_manager` should be the same EntityManager instance that the above invocation of `getManager()` used to return.

**Comment by makasim** [comment]
Thanks for reporting it. It's indeed has to be fixed

**Comment by tehplague** [comment]
A hot fix for existing applications is to add my second definition to the application's service definitions. This will override Payum's definition until the fix is in place.

**Comment by makasim** [comment]
@tehplague would you to work on PR? Alias solution looks good to me.
