### ISSUE TITLE
discounts

### ISSUE THREAD

**Issue by frechina** [Payum/PayumBundle#415]
Hi,

is there any extension that deals with discounts/coupons? 
I'm trying to make one by myself but if the discount is 100% then I can't follow the flow with totalAmount equals 0. How can I jump from 'prepare' to 'done' if the amount is equal 0?

any idea? Thank you

**Comment by makasim** [comment]
If the amount is equals zero you have to skip payment process completely. If you cannot do that you could try to introduce a gateway method that simply does nothing and use it for those  cases.

**Comment by frechina** [comment]
what do you mean by gateway method?
I'm storing the 'payment' status, so when the 'payment' is free (because a discount) I need to mark such payment as succeeded/captured

**Comment by makasim** [comment]
try use "offline" payment method for such cases.

**Comment by frechina** [comment]
awesome! this is exactly what I needed.
Thank you
