### ISSUE TITLE
How to get Recuring payment status

### ISSUE THREAD

**Issue by flierville** [Payum/PayumBundle#418]
Hello, I'am using your Bundle (great job) and I have a problem to get recuring payment status
For my test I'am using paypal sandbox (https://www.sandbox.paypal.com)

When I make a recuring Payment,
The $billingAgreementDetails is always "captured" and the $recurringPaymentStatus is always "pending".
So for validate the payment i chek the $billingAgreementDetails  like this :

```
$gateway->execute($status = new GetHumanStatus($billingAgreementDetails));
if ($status->isCaptured())
        {
          //Payment Valid etc.
```

In my BackEnd (admin) when I check the $billingAgreementDetails is always "captured"  and $recurringPaymentStatus is "pending" (**Yet the payment has been registered**)

```
$billingAgreementStorage = $this->get('payum')->getStorage('Fli\EventBundle\Entity\AgreementDetails');
$billingAgreementDetails = $billingAgreementStorage->find($idAgreement);
$recurringPaymentStorage = $this->get('payum')->getStorage('Fli\EventBundle\Entity\RecurringPaymentDetails');
$recurringPaymentDetails = $recurringPaymentStorage->find($idRecurringPayment);
$gateway->execute($status = new GetHumanStatus($recurringPaymentDetails));
var_dump($status);
$gateway->execute($status = new GetHumanStatus($billingAgreementDetails));
var_dump($status);
```

In the paypal **buyer** page if I **abort** the recurring payment :

- $billingAgreementDetails is always "**captured**"
- $recurringPaymentStatus is "pending"

I think it is not normal to have "captured" sate when it's aborted ?
I think it is not normal to have "pending" sate payment while it's ok in Paypal ?

Does the $gateway->execute get live Paypal Status or My local Database Status ?

Thank you very Much !

**Comment by makasim** [comment]
> I think it is not normal to have "captured" sate when it's aborted ?

the currently supported notific logic for subscriptions is very limited. It does not handle the abort on paypal side but could be added (should be easy). 

> I think it is not normal to have "pending" sate payment while it's ok in Paypal ?

What do you have inside payment details column in database? 

> Does the $gateway->execute get live Paypal Status or My local Database Status ?

If it is GetStatus request than it uses local state and does not perform any requests. 
If we are talking about Sync request than yes it does requests and syncs local state with the one from paypal side.

**Comment by flierville** [comment]
I Understand.
For have Paymen Status I mus re-use the Sync command ?

```
$gatewayName = 'paypal_express_checkout';
$gateway = $this->get('payum')->getGateway($gatewayName);

$recurringPaymentDetails = $recurringPaymentStorage->find($idRecurringPayment);
$gateway->execute(new Sync($recurringPaymentDetails));
$recurringPaymentStatus = new GetHumanStatus($recurringPaymentDetails);
$gateway->execute($recurringPaymentStatus);
$recuringPaymentReception = $recurringPaymentStatus->getFirstModel()->getDetails();
```
This code works for me, I have the online state and update in my local database

**Comment by makasim** [comment]
@flierville closing than?
