### ISSUE TITLE
could you please write a document show how to create a custom gateway please? 

### ISSUE THREAD

**Issue by videni** [Payum/PayumBundle#419]
every time , I try to create a custom gateway, I have to figure out how Payum works that way, it might not be that difficult , but it involves lots of analysis.

**Comment by makasim** [comment]
Payment gateways are vary a lot. One require a redirect, another a js snippet to be render. One have notifications another wont. The may provide a kind of sdk  or only an API (REST or SOAP). The credentials are different too. 

So what do you want me doing?

**Comment by makasim** [comment]
There is a skeleton repo (https://github.com/Payum/Skeleton). You can use that to setup a basic frame.

**Comment by makasim** [comment]
There are some ways the skeleton could be improved. 

It may have a script that sets your namespace and the name of gateway you'd like to develop.

It might have script that asks you questions and adjust the structure. 

If you'd like you can work on them and send me a PR. I'll be more than happy to merge them.

**Comment by videni** [comment]
@makasim , I am talking about how to write a custom gateway using Payum way,  no matter what a gateway needs redirect, or  js snippet to be render, but their main workflow  should be the same ,  for example.

1.   Extend Payum\Core\GatewayFactory\GatewayFactory

class CustomGatewayFactory extends GatewayFactory
{
    /**
     * {@inheritDoc}
     */
    protected function populateConfig(ArrayObject $config)
    {
      $config->defaults(array(
            'payum.factory_name' => 'custom',
            'payum.action.capture' => new CaptureOffsiteAction(),
            'payum.action.status' => new StatusAction(),
            'payum.action.convert_payment' => new ConvertPaymentAction(),
        ))
    //...
   }
}

2. Register this gateway to container

```
<service id=".payum.gateway_factory.customer" class="Payum\CustomGatewayFactory">
            <tag name="payum.gateway_factory_builder"  factory="custom"/>
        </service>
```

3. Enable that gateway in configuration
```
payum:
    gateways:
        custom:
            factory: custom
```
4.  Test gateway has successfully registered

Execute following code should list the gateway we just registered

`bin/console payum:gateway:debug `
```
custom (Payum\Core\Gateway):
	Actions:
	Payum\Core\Bridge\PlainPhp\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\AuthorizePaymentAction
	Payum\Core\Action\PayoutPayoutAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction
	Payum\YouYouBao\Action\CaptureOffsiteAction
	Payum\YouYouBao\Action\StatusAction
	Payum\AuthorizeNet\Aim\Action\ConvertPaymentAction

	Extensions:
	Payum\Core\Extension\EndlessCycleDetectorExtension

	Apis:
	Payum\Core\Bridge\Httplug\HttplugClient
```
# Then 

we can explain more specific case , such render js part.

**Comment by videni** [comment]
@makasim, the above way to register a GatewayFactory won't used the existing CoreGatewayFactory, this would leads to some problems, for example,  `prepend action ` will not work. any other way to register a custom gateway factory ?

**Comment by videni** [comment]
@makasim , I have used Symfony container factory solve this problem.  

1. create factory class

Acme\Bundle\DemoBundle\Factory\CustomGatewayFactoryFactory
```
class CustomGatewayFactoryFactory
{
    public function create()
    {
        return function($config, $coreGatewayFactory){
            return new CustomGatewayFactory($config,$coreGatewayFactory);
        };
    }
}
```

2. register that factory to container
```
  <service  id="acme.factory.custom_gateway_factory"    class="Acme\Bundle\DemoBundle\Factory\CustomGatewayFactoryFactory" public="false">
            <factory class=Payum\CustomGatewayFactory" method="create"/>
            <tag name="payum.gateway_factory_builder"  factory="custom"/>
        </service>

```

**Comment by rskuipers** [comment]
@videni Your snippet there helped me fix a problem where my gateway wasn't getting the same extensions as the core gateway. Thanks a lot! :+1:
