### ISSUE TITLE
Custom Action / Extension for Symfony3

### ISSUE THREAD

**Issue by mrmonsters** [Payum/PayumBundle#428]
Any of you guys creating custom actions for Symfony3, please do remember to set public: true (if all services are set to public: false by default) while registering new service, be it action or extension. I can't believe this silly missed configuration bugged me for days.

**Comment by makasim** [comment]
Sorry, I don't understand. What's the problem?

**Comment by mrmonsters** [comment]
Not code problem, but perhaps documentation for Symfony lacks update. I was going to create custom action based on https://github.com/Payum/Payum/blob/master/docs/symfony/container-tags.md to handle my business logics. However, I didn't get it to work earlier because I wasn't registering a public service. According to http://symfony.com/doc/current/service_container.html, my custom action works only when I register a public service explicitly.

**Comment by makasim** [comment]
We can add `public: true` to make this clear.

**Comment by mrmonsters** [comment]
Indeed. Thanks!
