### ISSUE TITLE
requires payum/core ^1.4 -> satisfiable by payum/core and php-http/client-implementation ^1.0 -> no matching package found 

### ISSUE THREAD

**Issue by viral2014** [Payum/PayumBundle#430]
Hello,

When I make composer require payum/payum-bundle I get the following error.

![issuegit](https://user-images.githubusercontent.com/31303925/29653482-9b2633fe-88c7-11e7-819f-5aba25a6f683.png)

**Comment by makasim** [comment]
everything in the output: `payum/core requires php-http/client-implementation -> no matching package found`.  and if you [search for this package on packagist](https://packagist.org/providers/php-http/client-implementation) you find plenty of them. 

The [doc](https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md#install) suggests you installing `php-http/guzzle6-adapter`
