### ISSUE TITLE
Got the Timeout Error After Success Payement on response back

### ISSUE THREAD

**Issue by shoaibgits** [Payum/PayumBundle#434]
I have integrate the Module with my zf2 framework everything is working fine payments are made but sometimes an error occur with the following information on response back to the website from paypal success payment

   Operation timed out after 5007 milliseconds with 0 bytes received

How to solve this one it is really need to be fixed to move my project on live server.

thanks!

**Comment by makasim** [comment]
Their sandbox is acting up periodically though the production api is very stable and I've never seen it timeouted.
