### ISSUE TITLE
Missing documentation about doUnsafeAction

### ISSUE THREAD

**Issue by webmake** [Payum/PayumBundle#435]
Hello, I missing some information about implementation together with `doUnsafeAction`. Let's say I have payment provider, which does not support IPN response customization, so that I could add token (in compare paypal can pass PAYMENTREQUEST_0_NOTIFYURL, so that token is passed). How to associate from post request with payment itself, that I could change payment status (without hackish way)? Is that possible at all?

**Comment by makasim** [comment]
Unfortunately, There is no doc for that part. You can look at be2bill offsite payment as a reference

**Comment by webmake** [comment]
Thanks a lot ! :) seems pretty valid solution via NotifyNullAction and widely used, but why all of them do not provide `NotifyNull` event? Is it magicaly resolved?

**Comment by webmake** [comment]
Solved, only needed to flip order null action must be before :)
