### ISSUE TITLE
Gateway config on the fly

### ISSUE THREAD

**Issue by Webvida** [Payum/PayumBundle#437]
Hi there, I need to store the config parameters for the gateways on a different server and have them "injected" when payum runs it's capture, authorize, etc... is it possible to set the config of payment gateways without storing them on the server which payum is running?

I have been messing around with having an event listener create the gateway before the controllers are hit, but I am having no luck...

So is there a way to "set" this config without saving it in doctrine or config files?

Thanks

**Comment by makasim** [comment]
Register api as a service and in the service take credentials from whatever place you want

**Comment by Webvida** [comment]
I actually took the "store config in the DB" approach which will work, but thanks for that! Now I have an issue in trying to update the config once I have saved it. I admit I am a bit of a symfony/payum noob and for the life of me I can't find a way to update the config once I have saved it!

It seems like payum does not take the normal approach with using the flush, etc if it does I just am not doing it right :(

I have seen examples like this:

```
$em = $this->getDoctrine()->getManager();
$entity = $em->getRepository('Bundle:Entity')->find($id);

$entity->setSomeProperty($propertyValue);

$em->flush();
```

So I am wondering how this would translate to the way payum does it with models and such. 

Thanks for your assistance thus far!

**Comment by Webvida** [comment]
my apologies I didn't realise the the findby was sending back an array and this was making my entity an array not an object - it worked once I array_shifted it. The code now works, sorry for wasting your time.

```
$gatewayConfigStorage = $this->getGatewayConfigStorage();
        $em = $this->getDoctrine()->getManager();
        
        $entity = array_shift($gatewayConfigStorage->findBy(
            [ 'gatewayName' => $customerId . '_' . $gateway ]
        ));
        
        $entity->setGatewayName( $customerId.'_'.$gateway );
        $entity->setFactoryName( $gateway );
        $entity->setConfig( $request->request->all() );
        
        $gatewayConfigStorage->update( $entity );
        
'''
