### ISSUE TITLE
Token class method doesn't return the correct type

### ISSUE THREAD

**Issue by MisterBiscuit** [Payum/PayumBundle#440]
I've installed the Payum Bundle and have created a sub class of Payum\Core\Model\Token.
When trying to extend the TokenInterface I get an error stating that "Declaration of Token->getDetails() must be compatible with TokenInterface->getDetails().
Apparently the TokenInterface->getDetails() returns an IdentityInterface type whereas Token->getDetails() returns an Identity type.
Would it be possible to get a fix for this, changing the Token->getDetails() return type to an IdentityInterface ?

**Comment by makasim** [comment]
Well, it should work.

Payum does not force any return type-hint at all, it is just a docblock https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Token.php#L45
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/DetailsAggregateInterface.php#L9

Could you post your token class, please?

**Comment by MisterBiscuit** [comment]
I've created 
- a class that extends Token and implements the following interface,
- an interface that extends TokenInterface.
They're currently empty to bring it down to the bare minimum.
Once I implement the interface my editor underlines the class name in red and the hover bubble indicates 

> Declaration of Token->getDetails() must be compatible with TokenInterface->getDetails().
Method declaration of super class is incompatible with implemented interface.

```
<?php

namespace Foo\Bar\Model;

use Payum\Core\Model\Token;

class PaymentToken extends Token implements PaymentTokenInterface
{
    
}
```
```
<?php

namespace Foo\Bar\Model;

use Payum\Core\Security\TokenInterface;

interface PaymentTokenInterface extends TokenInterface
{

}
```

**Comment by makasim** [comment]
You dont have to implement `PaymentTokenInterface ` interface, you are already extending a class which implements it.

**Comment by MisterBiscuit** [comment]
True enough, I just wanted to add an extra level of reliability where possible.
Thanks for the reply.

**Comment by MisterBiscuit** [comment]
Who is supposed to close the issue ?

**Comment by makasim** [comment]
Fell free to close it
