### ISSUE TITLE
How to configure the firewall

### ISSUE THREAD

**Issue by BenoitDuffez** [Payum/PayumBundle#442]
As far as I understood, with Paypal, we get automatic notifications to the notify URL when something changes on Paypal side (cancellation, payment, etc).

I want to configure the Symfony firewall to of course authorize requests from Paypal. Here's what I have with `debug:router`:

```
payum_capture_do_session   
payum_capture_do           
payum_authorize_do         
payum_notify_do_unsafe     
payum_notify_do            
payum_payout_do            
payum_refund_do            
payum_sync_do              
payum_cancel_do            
```

Which routes need to be protected (e.g. only used by an authenticated user), and which are accessed externally without authentication (e.g. from Paypal)?

**Comment by makasim** [comment]
There is no need of putting those url behind a firewal. They are unique, short-living, delete once not needed. 

As long as http verifier does not complain about the url, everything is fine.

**Comment by BenoitDuffez** [comment]
So there is no risk of these URLs being vulnerable should one token being exposed?

I mean I indeed have checked that all these URLs use unique short lived tokens, so I guessed it didn't matter as long as someone couldn't forge a token or capture one somehow and cause trouble with these URLs if they don't have a proper firewall.

**Comment by makasim** [comment]
If someone can steal the token they can do the same to any other sensitive info like session id or credentials.

**Comment by BenoitDuffez** [comment]
OK I'll guess I'll remove the firewall for all these routes then :-)

Thanks for the insanely fast support!
