### ISSUE TITLE
league/uri requirement (version 4 vs 5)

### ISSUE THREAD

**Issue by m-vo** [Payum/PayumBundle#446]
Are there any plans in the near future to use (or allow for) `league/uri` in version 5.* (required in `Payum/Core`)? Currently it's set to `^4.0` which conflicts with other projects I'm using that already require >5.

Here is the doc describing possible BC breaks when updateing to v5 - I'm not sure how much or if these affect Payum.
https://github.com/thephpleague/uri/blob/master/docs/upgrading/5.0.md

**Comment by makasim** [comment]
Payum uses it for very basic things like parse url or compose it. Like here https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php#L69 or here https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php#L25

You can search for `League\Uri` to find all the places.

I'd more then happy to merge a PR, though I am not going to do it myself in near future.

**Comment by m-vo** [comment]
Allright, then. 

Closed in favor of https://github.com/Payum/Payum/pull/723
