### ISSUE TITLE
How to get recurring payment notifications

### ISSUE THREAD

**Issue by BenoitDuffez** [Payum/PayumBundle#456]
I know that this has been asked more or less but I still can't wrap my head around that.

I have successfully set up recurring payments which show up fine on the sandbox account. However nothing is up to date on my symfony app. I have set up IPN however PayPal ignores the dynamic `NOTIFYURL` on purpose. There is the static unsecured route but that doesn't retrieve any useful information from the IPN and this ends up on an HTTP 500 response.

Am I supposed to use the static unsecured route? Why isn't it picking up the recurring payment profile from the IPN, then the agreement, then the token?

Or, or am I supposed to use the "secured" token-based route with recurring payments?

Or, do I simply have to deal with non up to date information? Or setup a sync Cron job? 

I have to issue invoices to customers upon each payment, and I don't want to use the PayPal service for that. I want custom made invoices.

Thanks!

**Comment by makasim** [comment]
You are supposed to use secured token per payment

**Comment by makasim** [comment]
The cron approach should work too. You  have to fetch a payment data and perform sync payment request with it.

**Comment by BenoitDuffez** [comment]
Re: use secured token per payment: PayPal doesn't use the `NOTIFYURL`:
See: https://stackoverflow.com/q/16483448/334493

It uses the static URL you can configure on the IPN enable/disable form:
![IPN URL](https://user-images.githubusercontent.com/802209/35321700-e2d9bec6-00e7-11e8-99ce-b4a3f4e4d9fe.png)
don't mind the `notifer` typo, I actually made the typo myself in Symfony routes so I have reported the typo on PayPal. I do receive the IPN and they fail.

(when they fail, it's _Request Notify{model: NULL} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker._)

**Comment by BenoitDuffez** [comment]
I feel like there is something we could do here to retrieve the token:

https://github.com/Payum/PayumBundle/blob/master/Controller/NotifyController.php#L14

Actually I don't understand why you create a new `Notify` with a `null` argument.

**Comment by BenoitDuffez** [comment]
For example, if I modify the `NotifyController::doUnsafeAction` as follows:

```

    public function doUnsafeAction(Request $request) {
        $profileId = $request->get('recurring_payment_id');
        if ($profileId) {
            $detailsFilter = sprintf('%%"PROFILEID":"%s"%%', $profileId);
            $registry = $this->getDoctrine();

            /** @var RecurringPaymentDetails $recurringPayment */
            $recurringPayment = $registry
                ->getRepository(RecurringPaymentDetails::class)
                ->createQueryBuilder('r')
                ->where('r.details like :detailsFilter')
                ->setParameter('detailsFilter', $detailsFilter)
                ->getQuery()
                ->getSingleResult();
            if ($recurringPayment) {
                /** @var AgreementDetails $agreement */
                $agreement = $recurringPayment->getAgreement();

                if ($agreement) {
                    if (isset($agreement['NOTIFYURL'])) {
                        $notifyUrl = $agreement['NOTIFYURL'];
                        $hash = substr($notifyUrl, strrpos($notifyUrl, '/') + 1);

                        /** @var PaymentToken $token */
                        $token = $registry->getRepository(PaymentToken::class)
                            ->findOneBy(['hash' => $hash]);

                        // If we could find the token, use the secure action; otherwise fallback to unsecure
                        if ($token) {
                            // Create fake request on the token target URL
                            $request = Request::create(
                                $token->getTargetUrl(),
                                $request->getMethod(),
                                $request->query->all(),
                                $request->cookies->all(),
                                $request->files->all(),
                                $request->server->all(),
                                $request->getContent()
                            );
                            $request->attributes->add([
                                'payum_token' => $hash,
                            ]);

                            return $this->doAction($request);
                        }
                    }
                }
            }
        }

        $gateway = $this->getPayum()->getGateway($request->get('gateway'));

        $gateway->execute(new Notify(null));

        return new Response('', 204);
    }
```

Then this makes the unsafe action behave like the safe action, by extracting the `PROFILEID` from the IPN. In my example, it was a token like `I-HDYF8EJDU653` (this one is fake).

**Comment by BenoitDuffez** [comment]
I have asserted the following:

POST on my app (validation of the final purchase order):

* create an agreement: I don't specify any notify URL (should I?)
* creates 2 tokens: one done token, and one capture token
* 302 to the capture token

the capture token (handled by PayumBundle, not my app):

* creates a notify token
* 302 to PayPal

back from PayPal:

* create a recurring payment
* delete the capture token

The actual notify URL is created by PayumBundle and I have no control over what's sent to PayPal at this moment. When I create the agreement (on the POST, first step), there is no notify token created yet.

I can see that the notify URL is handled by the `PurchaseAction` in `paypal-express-checkout-nvp`. This action sets the `PAYMENTREQUEST_0_NOTIFYURL` to the notify token target URL, then it executes:

* SetExpressCheckout
* Sync
* no ConfirmOrder because my amount is zero (no subscription fee)
* AuthorizeToken
* Sync

So I believe that PayPal has been made aware of the `PAYMENTREQUEST_0_NOTIFYURL` and simply ignores it (as analyzed by the StackOverflow user, as linked on my first comment here).

Did I do something wrong? Note that I followed the guide at https://github.com/Payum/Payum/blob/master/docs/paypal/express-checkout/recurring-payments-basics.md

**Comment by BenoitDuffez** [comment]
Or, (sorry for the flood of questions, I'm just trying to wrap my head around all of that)

The purpose of PayumBundle is to integrate nicely Payum with Symfony, handle some of the actions automatically (like capture), but the purpose is *NOT* to handle everything, such as IPN for recurring payments.

If that's the case, then the implementation I have made in `doUnsafeAction` has to be moved in one of my controllers, and then handle the invoice myself when I receive the IPN.

So which is it? :-)

(I hope that's OK with you when I submit so much information and questions at once. Hopefully this will be useful for someone else later on!)

**Comment by BenoitDuffez** [comment]
I have implemented the `doUnsafeAction` modification on my staging server and it started to process IPNs.

I don't understand why they return 204 when PayPal expects them to return 200:

* [4th bullet in "IPN Overview"](https://github.com/paypal/ipn-code-samples/)
* [one sample verifies the IPN and returns 200](https://github.com/paypal/ipn-code-samples/blob/master/php/example_usage.php)

Though I agree with you that an empty response should be a 204, PayPal has explicitly required us to return 200.

**Comment by BenoitDuffez** [comment]
Disregard the issue about 204, PayPal accept them despite them saying they want 200. It took a while for the IPN to pick up but now they show up as success on IPN history.

**Comment by BenoitDuffez** [comment]
I don't have an answer to my initial question (why PayPal won't use the notify URL for recurring payments), but in the end I fixed my issues with:

* add paypal-ipn dependency
* a new route on my controller to receive all IPNs from PayPal
* when receiving an IPN:
    * validate the IPN with the new dependency
    * if `txn_type` is `recurring_payment_profile_created` then send purchase confirmation email to customer
    * if `txn_type` is `recurring_payment`:
         * execute a `Sync` on the recurring payment 
         * create invoice and email it to customer
    * return 204

I'm not sure that's how I should do it or if these are good practises, but it seems to be exactly what I wanted with minimal code.
