### ISSUE TITLE
How to convert a payment into a subscription?

### ISSUE THREAD

**Issue by KotetsuNoAkai** [Payum/PayumBundle#458]
I have a project developed in symfony in which paypal payments are made, but I want to convert these payments into an annual subscription.

This is the process I'm following right now:

`public function processPaymentClientAction(Sellers $sold)
{
    $storage = $this->get('payum')->getStorage(Payment::class);

    $payment = $storage->create();
    $payment->setNumber(uniqid());
    $payment->setCurrencyCode('EUR');
    $payment->setTotalAmount($sold->getFinalPriceTax()*100);
    $payment->setDescription($sold->getProduct()->getName());
    $payment->setClientId($this->getUser()->getId());
    $payment->setClientEmail($this->getUser()->getEmail());

    $storage->update($payment);

    $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
        'paypal',
        $payment,
        'finishBuy' // the route to redirect after capture
    );

    return $this->redirect($captureToken->getTargetUrl());
}`
Use the PayumBundle with paypal_express_checkout

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/docs/paypal/express-checkout/recurring-payments-basics.md

**Comment by KotetsuNoAkai** [comment]
I reading the documentation, but using symfony, how i can do this in symfony
use Payum\Core\Storage\FilesystemStorage;

$agreementClass = 'App\Model\AgreementDetails';
$recurringPaymentClass = 'App\Model\RecurringPaymentDetails';

$storages[$agreementClass] = new FilesystemStorage(
    __DIR__.'/storage',
    $agreementClass
);
$storages[$recurringPaymentClass] = new FilesystemStorage(
    __DIR__.'/storage',
    $recurringPaymentClass
);

**Comment by sovetski** [comment]
@makasim It does not explain how to implement with this **bundle**

**Comment by pierredup** [comment]
@sovetski The implementation will be mostly the same with the following changes:

* `create_recurring_payment.php` will be a Symfony controller instead of a PHP file
	* E.G
	* ```php
	    class PaymentBundle {
            public function recurringPayment(Payum $payum): Response {
                // .....
                // Same code as `create_recurring_payment.php` from the docs, adjusted for Symfony
            }
        }
	    ```
* The `prepare.php` would be the same as the `prepare` action when using the bundle (https://payum.gitbook.io/payum/symfony/get-it-started#create-payment-and-redirect-the-user), but with the following changes added (taken from the linked docs page)
	* ````php
	    // PaymentController
	    public function prepare(Payum $paym): Response {
            // Prepare action
            $agreement = $storage->create();
            $agreement['PAYMENTREQUEST_0_AMT'] = 0; // For an initial amount to be charged please add it here, eg $10 setup fee
            $agreement['L_BILLINGTYPE0'] = Api::BILLINGTYPE_RECURRING_PAYMENTS;
            $agreement['L_BILLINGAGREEMENTDESCRIPTION0'] = "Insert some description here";
            $agreement['NOSHIPPING'] = 1;
            $storage->update($agreement);
        }
	    ```
* When creating the capture token, the route to your `recurringPayment` action should be set:
	* ```php
	    $captureToken = $payum
        ->getTokenFactory()
        ->createCaptureToken(
            'paypal',
            $agreement,
            'create_recurring_payment' // <- route name for the recurringPayment action
        );
	    ```
