### ISSUE TITLE
Symfony4 - Profiler doesn't work

### ISSUE THREAD

**Issue by waeyy** [Payum/PayumBundle#468]
Hi,

I have some trouble using the PayumBundle and the profiler of symfony together. When i activate the PayumBundle, Symfony is not able to load the profiler and the routes concerned and i got this on the profiler toolbar at the bottom : **An error occurred while loading the web debug toolbar.**

And when i deactivate the PayumBundle, the web debug toolbar works.

Any ideas ? 

Thank you.

**Comment by nicolasricci** [comment]
@waeyy it's been fixed in this PR #461 but only available on the master branch for now.
@makasim could you please tag a new version with this fix?

**Comment by s7anley** [comment]
Hi @makasim, will you have time to create new release version?

**Comment by pierredup** [comment]
Closing since a fix was released in version [2.3.1](https://github.com/Payum/PayumBundle/releases/tag/2.3.1)
