### ISSUE TITLE
New release for Sf 4 compatibility ?

### ISSUE THREAD

**Issue by ogizanagi** [Payum/PayumBundle#469]
Hi there 👋 

There is no new release of this bundle since 9 January while some PRs were merged fixing issues with Symfony 4. Could we get a new one, please? :)

Thanks for all the work!

**Comment by makasim** [comment]
https://github.com/Payum/PayumBundle/releases/tag/2.3.1

**Comment by ogizanagi** [comment]
That was fast 🚄 Thanks a lot!
