### ISSUE TITLE
A better information in readme about the location of payum.yaml

### ISSUE THREAD

**Issue by ralexy** [Payum/PayumBundle#473]
Hello,

In the readme we don't have the location of the payum.yaml which is located at : config/packages/payum.yaml!

I think it's better to be more accurate about that :-)!

**Comment by makasim** [comment]
Hi 

Feel free to submit a PR that fixes it.

**Comment by tarlepp** [comment]
There should be a flex recipe to make this automatically within sf4 applications.

**Comment by makasim** [comment]
The doc is for Symfony2\3

**Comment by pierredup** [comment]
A flex recipe is available at https://github.com/symfony/recipes-contrib/tree/master/payum/payum-bundle/2.4
