### ISSUE TITLE
Sandbox requires a boolean, but Symfony 4 and DotEnv only provide strings

### ISSUE THREAD

**Issue by BenoitDuffez** [Payum/PayumBundle#486]
I'm using Paypal ExpressCheckout NVP API.

I've migrated to Symfony 4.2 and moved most of the dynamic parameters to DotEnv files. I'm having an environment parameter called `paypal_sandbox` which is `true` in development/test environments, and `false` in production.

This doesn't work, as the environment variable is always a string, and the NVP API strictly checks for a boolean at [Nvp/Api.php:328](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Api.php#L328)

This check fails and an exception is raised.

Is there a way to intercept the value to cast it as a boolean? or would it be possible to compare the value with `=== "true"` for example instead of the static `is_boolean`?

**Comment by makasim** [comment]
you could cast env var to bool with env resolvers 

https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables

**Comment by BenoitDuffez** [comment]
Brilliant, thanks. For those interested:

`config/packages/payum.yaml`:

    payum:
      gateways:
        xyz:
          factory: paypal_express_checkout
          username: '%env(paypal_user)%'
          password: '%env(paypal_password)%'
          signature: '%env(paypal_signature)%'
          sandbox: '%paypal_sandbox%'
    
    parameters:
      paypal_sandbox: '%env(bool:paypal_sandbox)%'

`.env` (production):

    paypal_sandbox=false

`.env.local` (development):

    paypal_sandbox=true
