### ISSUE TITLE
Twig 3 support

### ISSUE THREAD

**Issue by AlexeyKosov** [Payum/PayumBundle#506]
Is it possible to add support for twig/twig "^3.0" so that composer does not crash when twig 3 is already installed?

**Comment by carlos-mg89** [comment]
Although not a solution for the Twig 3 support, it would very likely work for people not having problems with downgrading Twig to the latest 2 version: https://github.com/Payum/Payum/issues/840

**Comment by Ji97** [comment]
Hello,

I'm facing the same issue with No possibility to downgrade. Thanks

**Comment by jkabat** [comment]
@makasim is possible to allow Twig 3 in payum bundle while it is already supported by core?

**Comment by pierredup** [comment]
@jkabat Twig 3 support in core is only available in the master branch for now. If you change your `composer.json` to install the master branch, then you should be able to install Twig 3 as well (there is nothing in this bundle preventing Twig 3 from being installed)

```json
{
    "require": {
        "payum/core": "dev-master"
    }
}
```

**Comment by jkabat** [comment]
@pierredup I knew that, I've just seen Twig v2 upper dependency in Payum bundle itself... my bad - after better look I realized it was only in DEV section...

**Comment by pierredup** [comment]
Closing since Twig 3 is supported in the 2.4.2 release
