### ISSUE TITLE
use Doctrine\Persistence\ObjectManager  instead Doctrine\Common\Persistence\ObjectManager

### ISSUE THREAD

**Issue by martygraphy** [Payum/PayumBundle#520]
Hello, 
I receive this error when I want to make a payment: 

`Argument 1 passed to Payum\Core\Bridge\Doctrine\Storage::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given, called in /var/www/html/var/cache/dev/ContainerQsE4e9C/srcApp_KernelDevDebugContainer.php on line 1617`

I saw that an intervention had taken place on the Payum/Core directory correcting this problem: 

https://github.com/Payum/Core/commit/4b8987cfcd7201d2bd81675cdc85a667de45eb9a

Would it be possible to use the latest version of payum/core in the payum/payum-bundle ? Because version 1.6 does not include this feature. 

Sincerely

Marc-Antoine

**Comment by jkabat** [comment]
Seems like you use recent Doctrine/Persistence library. To solve the issue you should require Payum/Core:dev-master  version until new stable version is tagged.

**Comment by martygraphy** [comment]
@jkabat  Hello, 
Thank you for your answer. 
I'm not sure I understand your message, I use payum-bundle for symfony which uses payum-core.

Why do I have to use payum/payum?

**Comment by martygraphy** [comment]
Oh ok sorry my bad  !  Thank you @jkabat  !
