### ISSUE TITLE
DBAL 3 - incompatible

### ISSUE THREAD

**Issue by bertoferrero** [Payum/PayumBundle#531]
Payum uses json_array mapping which, as it is exposed in the following link, it is removed on DBAL 3 version. It could be easily fixed just changing this mapping for json
https://github.com/doctrine/orm/issues/9078

I tried to change it and create a new pull request but... once I had it, my composer was not able to resolve the right repository because payum/bundle requires payum/payum and payum/core and, always, one of them generated any conflict. My fault sure.

**Comment by pierredup** [comment]
> It could be easily fixed just changing this mapping for json

@bertoferrero This is a BC break if we just change the mapping (Due to the difference in behaviour in the `json_array` and `json` types). 

See payum/payum#922 as well

**Comment by Chris53897** [comment]
@pierredup This Issue could probably be closed, as your PR is merged in https://github.com/Payum/Payum/commit/da5b9256190aa07c27a342a285f34000540e5383 and 1.7.0 was released on 05.01.2022.
