### ISSUE TITLE
Sylius is not notify when payment success after first payment fail

### ISSUE THREAD

**Issue by sdechomets** [Payum/PayumBundle#532]
Hello,

Same issue has already been reported here https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/issues/2

As we use Monetico, do we have to switch to fluxSE version to solve this problem or can we expect a resolution in this version of the bundle ?

Thx

**Comment by pierredup** [comment]
@sdechomets This bundle and Payum core doesn't provide any integration for Monetico. You can use the plugin at FLUX-SE/SyliusPayumMoneticoPlugin to get that integration.

**Comment by sdechomets** [comment]
Ok, but it seemed to work very well with Monetico except for this problem, however we're going to switch if it's your recommendation.

Thx

**Comment by sdechomets** [comment]
My bad, we use prometee/sylius-payum-monetico-plugin, sorry for the convenience
