### ISSUE TITLE
Drop support of < php 7.4 ?

### ISSUE THREAD

**Issue by Chris53897** [Payum/PayumBundle#533]
Hi,

only < 10% are useing < php 7.4
https://packagist.org/packages/payum/payum-bundle/php-stats#2

Can this bundle drop the support for < php 7.4 and start useing the new language features?

WDYT?

Greetz

**Comment by pierredup** [comment]
Hi @Chris53897

I think it makes sense to drop support for older PHP versions in the next minor version (2.5). Are you up for giving it a go and creating a PR?

**Comment by Chris53897** [comment]
@pierredup thanks for the fast response. I am already working on the PR ;)

**Comment by Chris53897** [comment]
Code is megred into master (in another PR). I will close this
