### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by adrienlamotte** [Payum/PayumBundle#552]
Hello,
Any chance to make it compatible with Symfony 7?
Thanks!

**Comment by kabudu** [comment]
I second this.

**Comment by kabudu** [comment]
@adrienlamotte It looks like this has already been done in master, but hasn't been released yet.

**Comment by loic425** [comment]
@pierredup @sovetski
Could you make a release at least an alpha, to unblock Symfony 7 support on Sylius please?
https://github.com/Sylius/Sylius/issues/15481

We are very close to the SF7 support, please help use.

**Comment by pierredup** [comment]
Version [2.6.0](https://github.com/Payum/PayumBundle/releases/tag/2.6.0) has been released which includes Symfony 7 support.
