### ISSUE TITLE
guzzle6 adapter is no longer maintained

### ISSUE THREAD

**Issue by sovetski** [Payum/PayumBundle#562]
The package is no longer maintained as mentionned here: https://github.com/php-http/guzzle6-adapter

They suggest https://github.com/php-http/guzzle7-adapter/

But on the error message it suggest the version 6:

`The httplug.message_factory could not be guessed. Install one of the following packages: php-http/guzzle6-adapter, zendframework/zend-diactoros. You can also overwrite the config option with your implementation.`

![image](https://github.com/Payum/PayumBundle/assets/13520683/0af2fd53-6477-4594-b910-99ffa5b2471f)

And also, on Symfony we already have an HTTP client: https://symfony.com/doc/current/http_client.html

Can we use it instead? There is a related issue which is closed but I don't see any explanation on if it is implemented/possible or not

Thanks in advance

**Comment by pierredup** [comment]
@sovetski Thanks for the report.

PayumBundle already uses guzzle7 adapter by default.
https://github.com/Payum/PayumBundle/blob/e2a3ffee369efdd414c9cb13cd2bd09eb93beaa8/composer.json#L59

Also the next version of Payum will use `php-http/discovery` by default to detect a PSR-18 compatible client (see Payum/Payum#975). So this will be resolved with the release of Payum V2 (and the corresponding PayumBundle release)

**Comment by sovetski** [comment]
@pierredup thank you for the clarification. Do you know when the v2 will be released? I know that you work on this on your free time and it is difficult to give a date, but the pull request #975 exist since november 2023 so I am asking my self if it will take a lot of time, if yes I will try to use another alternative. Thanks in advance!
